Repository Evarisk/Digirisk, pull requests merged in 2022-10, with the labels that each got.

#2634 Fix trigger, bug fix and add table SQL for digirisk trigger event
  admin/config/event.php
  class/actions_digiriskdolibarr.class.php
  class/digiriskstandard.class.php
  core/modules/digiriskdolibarr/digiriskelement/accident/mod_accident_standard.php
  core/modules/digiriskdolibarr/digiriskelement/evaluator/mod_evaluator_standard.php
  core/modules/digiriskdolibarr/digiriskelement/groupment/mod_groupment_standard.php
  core/modules/digiriskdolibarr/digiriskelement/workunit/mod_workunit_standard.php
  core/modules/digiriskdolibarr/riskanalysis/risk/mod_risk_standard.php
  core/modules/digiriskdolibarr/riskanalysis/riskassessment/mod_riskassessment_standard.php
  core/modules/digiriskdolibarr/riskanalysis/risksign/mod_risksign_standard.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/digiriskdolibarr_projectcreation_action.tpl.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
  lib/digiriskdolibarr.lib.php
  lib/digiriskdolibarr_function.lib.php
  sql/data.sql
  sql/llx_c_digiriskdolibarr_action_trigger.key.sql
  sql/llx_c_digiriskdolibarr_action_trigger.sql
  sql/update.sql
Labels: Bug, Amélioration, 5

#2638 Fix event const and data sql event
  core/modules/modDigiriskDolibarr.class.php
  sql/data.sql
Labels: Amélioration, 2

#2648 #2411 [CSS] add: CSS on Patchnote
  css/digiriskdolibarr.css
  css/digiriskdolibarr.min.css
  css/scss/element/_element.scss
  css/scss/element/_patchnote.scss
Labels: Amélioration, 2, Integration
