Repository Evarisk/Digirisk, pull requests merged in 2022-09, with the labels that each got.

#2233 [Ticket] add: digiriskelement name on the right of element ref
  core/tpl/digiriskdolibarr_dashboard_ticket.tpl.php
Labels: Amélioration, 1

#2383 fix: better error management in digiriskHeader
  lib/digiriskdolibarr_function.lib.php
Labels: Amélioration, 0

#2481 #2315 [Trigger] add: infos for triggers
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 3
