Repository Evarisk/Digirisk, pull requests merged in 2023-12, with the labels that each got.

#3589 #3588 [Document] fix: signature object cant use function getFullName
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/registerdocument/doc_registerdocument_odt.modules.php
Labels: Bug, 0

#3591 #3590 [Trigger] add: register document trigger
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 0

#3600 #3599 [Tools] fix: remove end function array useless here
  view/digirisktools.php
Labels: Bug, 1

#3602 #3601 [Dashboard] fix: clean and improve check accidents function getNbAccidentsLast3years
  class/accident.class.php
Labels: Bug, 1

#3603 #3573 [DigiriskStandard] fix: generation ODT with useless parameters
  view/digiriskelement/digiriskelement_listingrisksaction.php
  view/digiriskelement/digiriskelement_listingrisksphoto.php
  view/digiriskstandard/digiriskstandard_informationssharing.php
  view/digiriskstandard/digiriskstandard_legaldisplay.php
  view/digiriskstandard/digiriskstandard_registerdocument.php
Labels: Bug, 2

#3604 #3587 [Accident] add: archive status
  class/accident.class.php
  view/accident/accident_card.php
Labels: Amélioration, 1

#3606 #3605 [ODT] fix: subdir param useless because missing require mod issue for fix it
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/firepermitdocument/doc_firepermitdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/informationssharing/doc_informationssharing_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/legaldisplay/doc_legaldisplay_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksaction/doc_listingrisksaction_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksphoto/doc_listingrisksphoto_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/preventionplandocument/doc_preventionplandocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/registerdocument/doc_registerdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/doc_riskassessmentdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/ticketdocument/doc_ticketdocument_odt.modules.php
Labels: Bug, 2, ODT/PDF

#3607 #3595 [Admin] add: config title and subtitle multi_company_ticket_public_interface
  admin/ticket/ticket.php
  langs/fr_FR/digiriskdolibarr.lang
  public/ticket/create_ticket.php
Labels: Amélioration, 2

#3609 #3518 [PreventionPlan] add: categories
  class/actions_digiriskdolibarr.class.php
  class/firepermit.class.php
  class/preventionplan.class.php
  core/modules/modDigiriskDolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
  sql/firepermit/llx_categorie_firepermit.key.sql
  sql/firepermit/llx_categorie_firepermit.sql
  sql/preventionplan/llx_categorie_preventionplan.key.sql
  sql/preventionplan/llx_categorie_preventionplan.sql
  view/firepermit/firepermit_card.php
  view/preventionplan/preventionplan_card.php
Labels: Amélioration, 2

#3611 #3610 [Lib] add: cursor pointer on morecss
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_function.lib.php
Labels: Amélioration, 0

#3533 #3532 amélioration de la fiche de d'unité de travail
  documents/doctemplates/workunitdocument/template_workunitdocument.odt
Labels: Amélioration, 3, ODT/PDF

#3620 #3619 [Hook] fix: hook name saturne
  class/actions_digiriskdolibarr.class.php
Labels: Bug, 0

#3631 #3630 [Mod] add: import risk/riskassessment
  core/modules/modDigiriskDolibarr.class.php
Labels: Amélioration, 2

#3632 #3629 [RiskAssessment] fix: add missing input in edit modal
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view_edit_modal.tpl.php
Labels: Bug, 2

#3633 #3594 [Investigation] add: task label in document
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/doc_accidentinvestigationdocument_odt.modules.php
  documents/doctemplates/accidentinvestigationdocument/template_accidentinvestigationdocument.odt
Labels: Amélioration, 1, ODT/PDF

#3634 #3612 [Accident] fix: view and pages
  class/accident.class.php
  class/actions_digiriskdolibarr.class.php
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
  lib/digiriskdolibarr_accident.lib.php
  view/accident/accident_card.php
  view/accident/accident_metadata.php
Labels: Bug, 3

#3636 #3635 [PP/FP] fix: move categories field on the right
  view/firepermit/firepermit_card.php
  view/preventionplan/preventionplan_card.php
Labels: Amélioration, 0

#3638 #3637 [Hook] fix: remove hook category now in saturne
  class/actions_digiriskdolibarr.class.php
Labels: Amélioration, 0

#3642 #3640 [Riskassessment] fix: show cotation wrongly in single/list/edit view
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view.tpl.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view_single.tpl.php
  css/digiriskdolibarr.min.css
  css/scss/table/_evaluation.scss
Labels: Bug, 1

#3645 #3644 [Mod] add: conf pp fp trigger unvalidate
  core/modules/modDigiriskDolibarr.class.php
  sql/data.sql
  sql/update.sql
Labels: Bug, 0

#3650 #3649 [Mail] fix: if getpost model then action also presend
  view/digiriskstandard/digiriskstandard_riskassessmentdocument.php
  view/firepermit/firepermit_card.php
  view/preventionplan/preventionplan_card.php
Labels: Bug, 0

#3647 #3211 [Document] fix: better display and attendant
  class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/doc_accidentinvestigationdocument_odt.modules.php
  documents/doctemplates/accidentinvestigationdocument/template_accidentinvestigationdocument.odt
  documents/doctemplates/groupmentdocument/template_groupmentdocument.odt
  documents/doctemplates/listingrisksaction/template_listingrisksaction.odt
  documents/doctemplates/riskassessmentdocument/template_riskassessmentdocument.odt
  documents/doctemplates/workunitdocument/template_workunitdocument.odt
Labels: Bug, 2

#3643 #3641 [Mod] add: new version number 9.14.1
  README.md
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 0
