Repository Evarisk/Digirisk, pull requests merged in 2023-10, with the labels that each got.

#3302 fix picto
  admin/securityconf.php
  class/actions_digiriskdolibarr.class.php
  class/digiriskelement.class.php
  class/digiriskelement/groupment.class.php
  class/digiriskelement/workunit.class.php
  class/digiriskstandard.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_inheritedrisklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_sharedrisklist_view.tpl.php
  core/tpl/riskanalysis/risksign/digiriskdolibarr_inheritedrisksignlist_view.tpl.php
  core/tpl/riskanalysis/risksign/digiriskdolibarr_risksignlist_view.tpl.php
  core/tpl/riskanalysis/risksign/digiriskdolibarr_sharedrisksignlist_view.tpl.php
  view/accident/accident_card.php
  view/accident/accident_list.php
  view/accident/accident_metadata.php
  view/digiriskelement/digiriskelement_card.php
  view/digiriskelement/digiriskelement_register.php
  view/digiriskstandard/digiriskstandard_riskassessmentdocument.php
  view/digirisktools.php
  view/firepermit/firepermit_card.php
  view/firepermit/firepermit_list.php
  view/preventionplan/preventionplan_card.php
  view/preventionplan/preventionplan_list.php
  view/ticket/dashboard_ticket.php
Labels: Amélioration, 3

#3301 fix ticket
  core/tpl/digiriskdolibarr_dashboard_ticket.tpl.php
  js/digiriskdolibarr.min.js
  js/modules/ticket.js
  langs/fr_FR/digiriskdolibarr.lang
  view/digiriskelement/digiriskelement_organization.php
  view/digiriskelement/digiriskelement_register.php
  view/ticket/ticketstats.php
Labels: Amélioration, 2

#3320 fix digiriskelement
  admin/config/digiriskelement.php
  class/actions_digiriskdolibarr.class.php
  class/digiriskelement.class.php
  class/digiriskstandard.class.php
  class/evaluator.class.php
  class/riskanalysis/risk.class.php
  class/riskanalysis/riskassessment.class.php
  class/riskanalysis/risksign.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/informationssharing/doc_informationssharing_odt.modules.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
  core/tpl/riskanalysis/risksign/digiriskdolibarr_risksignlist_view.tpl.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
  js/digiriskdolibarr.min.js
  js/modules/navigation.js
  lib/digiriskdolibarr_function.lib.php
  view/digiriskelement/digiriskelement_card.php
  view/digiriskelement/digiriskelement_evaluator.php
  view/digiriskelement/digiriskelement_listingrisksaction.php
  view/digiriskelement/digiriskelement_listingrisksphoto.php
  view/digiriskelement/digiriskelement_register.php
  view/digiriskelement/digiriskelement_risk.php
  view/digiriskelement/digiriskelement_risksign.php
  view/digiriskstandard/digiriskstandard_legaldisplay.php
Labels: Amélioration, 5

#3303 #3274 [Accident] fix: functional use and display of accident related obj
  admin/config/accident.php
  class/accident.class.php
  core/modules/modDigiriskDolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
  sql/accident/llx_c_lesion_localization.sql
  sql/accident/llx_c_lesion_nature.sql
  sql/accident/llx_c_relative_location.sql
  sql/update.sql
  view/accident/accident_card.php
  view/accident/accident_list.php
  view/accident/accident_metadata.php
  view/accident/accident_metadata_lesion.php
Labels: Amélioration, 3

#3270 #3260 [Investigation] fix: issues bring by saturne integration
  class/accident_investigation.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/doc_accidentinvestigationdocument_odt.modules.php
  core/modules/modDigiriskDolibarr.class.php
  documents/doctemplates/accidentinvestigationdocument/template_accidentinvestigationdocument.odt
  view/accident_investigation/accident_investigation_card.php
  view/accident_investigation/accident_investigation_list.php
Labels: Amélioration, 3

#3312 #3311 [DigiriskElement] fix: replace fetchFromParent by fetchAll
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
Labels: Bug, 0

#3313 #3305 [Trigger] fix: trigger and event
  admin/event.php
  class/accident.class.php
  class/digiriskdocuments.class.php
  class/evaluator.class.php
  class/firepermit.class.php
  class/preventionplan.class.php
  class/riskanalysis/risk.class.php
  class/riskanalysis/riskassessment.class.php
  class/riskanalysis/risksign.class.php
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
  lib/digiriskdolibarr.lib.php
  sql/data.sql
  view/digiriskelement/digiriskelement_card.php
  view/digiriskelement/digiriskelement_listingrisksaction.php
  view/digiriskelement/digiriskelement_listingrisksphoto.php
  view/digiriskstandard/digiriskstandard_informationssharing.php
  view/digiriskstandard/digiriskstandard_legaldisplay.php
Labels: Amélioration, 3

#3324 #3311 [AccidentWorkstop] add: fetchFromParent instead of fetchall
  class/accident.class.php
  class/accidentinvestigation.class.php
  class/actions_digiriskdolibarr.class.php
  class/digiriskelement.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/doc_accidentinvestigationdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
  core/modules/modDigiriskDolibarr.class.php
  documents/doctemplates/accidentinvestigationdocument/template_accidentinvestigationdocument.odt
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_accidentinvestigation.lib.php
  sql/accident/llx_categorie_accident_investigation.key.sql
  sql/accidentinvestigation/index.php
  sql/accidentinvestigation/llx_c_accidentinvestigation_attendants_role.sql
  sql/accidentinvestigation/llx_categorie_accidentinvestigation.key.sql
  sql/accidentinvestigation/llx_categorie_accidentinvestigation.sql
  sql/accidentinvestigation/llx_digiriskdolibarr_accident_investigation.key.sql
  sql/accidentinvestigation/llx_digiriskdolibarr_accident_investigation.sql
  sql/data.sql
  sql/update.sql
  view/accident/accident_card.php
  view/accident/accident_metadata.php
  view/accident/accident_metadata_lesion.php
  view/accidentinvestigation/accidentinvestigation_card.php
  view/accidentinvestigation/accidentinvestigation_list.php
  view/accidentinvestigation/index.php
Labels: Amélioration, 0

#3329 #3293 [Project] add: project document in configuration
  class/actions_digiriskdolibarr.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/projectdocument/pdf_orque_projectdocument.modules.php
  core/modules/modDigiriskDolibarr.class.php
Labels: Amélioration, 2

#3330 #3285 [DigiriskElement] add: notice on empty organization
  langs/fr_FR/digiriskdolibarr.lang
  view/digiriskelement/digiriskelement_organization.php
Labels: Amélioration, 1

#3323 #3286 [DigiriskUsers] fix: remove group by clause
  view/digiriskusers.php
Labels: Bug, 2

#3325 #3281 #3283 [Dashboard] fix: rework dashboard info
  class/accident.class.php
  class/digiriskdolibarrdashboard.class.php
  class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
  class/digiriskresources.class.php
  class/digirisktask.class.php
  class/evaluator.class.php
  class/riskanalysis/risk.class.php
  view/digiriskstandard/digiriskstandard_card.php
Labels: Bug, 3

#3328 #3287 [TPL] fix: projet creation group
  core/tpl/digiriskdolibarr_projectcreation_action.tpl.php
Labels: Bug, 3

#3339 #3280 [PreventionPlan] fix: document/workflow/view/SQL
  class/digiriskdolibarrdocuments/preventionplandocument.class.php
  class/preventionplan.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/preventionplandocument/doc_preventionplandocument_odt.modules.php
  documents/temp/index.php
  sql/preventionplan/llx_digiriskdolibarr_preventionplan.sql
  sql/preventionplan/llx_digiriskdolibarr_preventionplandet.sql
  sql/update.sql
  view/preventionplan/preventionplan_card.php
Labels: Bug, 3

#3340 #3280 [FirePermit] fix: document/workflow/view/SQLfix: document/workflow/view/SQL
  class/digiriskdolibarrdocuments/firepermitdocument.class.php
  class/firepermit.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/firepermitdocument/doc_firepermitdocument_odt.modules.php
  sql/firepermit/llx_digiriskdolibarr_firepermit.sql
  sql/firepermit/llx_digiriskdolibarr_firepermitdet.sql
  sql/update.sql
  view/firepermit/firepermit_card.php
Labels: Bug, 3

#3347 #3345 [Trad] fix: change some translation
  langs/fr_FR/digiriskdolibarr.lang
  view/accidentinvestigation/accidentinvestigation_card.php
Labels: Traduction, 0

#3350 #3348 [Triggers] add: missing triggers and fix ref PROV
  class/digiriskelement.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 2

#3355 #3354 [Conf] fix: remove backslash n in event tab
  admin/event.php
Labels: Amélioration, 0

#3361 #3356 [ODT] fix: missing element in various ODT
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/preventionplandocument/doc_preventionplandocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/doc_riskassessmentdocument_odt.modules.php
  documents/doctemplates/listingrisksaction/template_listingrisksaction.odt
  documents/doctemplates/listingrisksphoto/template_listingrisksphoto.odt
  documents/doctemplates/riskassessmentdocument/template_riskassessmentdocument.odt
  documents/doctemplates/workunitdocument/template_workunitdocument.odt
Labels: Bug, 3

#3362 #3333 [DigiriskElement] fix: navigation href
  js/digiriskdolibarr.min.js
  js/modules/navigation.js
  lib/digiriskdolibarr_function.lib.php
Labels: Amélioration, 2

#3365 #3327 [Index] fix: projectcreation
  core/tpl/digiriskdolibarr_projectcreation_action.tpl.php
  digiriskdolibarrindex.php
Labels: Bug, 0

#3367 #3304 [Task] fix: display user creat name instead of current user
  class/digirisktask.class.php
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_single_view.tpl.php
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_view.tpl.php
Labels: Bug, 1

#3370 #3357 [PreventionPlan] fix: available digirisk element for lines
  view/firepermit/firepermit_card.php
  view/preventionplan/preventionplan_card.php
Labels: Bug, 2

#3373 fix check access
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/digiriskdolibarr_projectcreation_action.tpl.php
  lib/digiriskdolibarr_digiriskstandard.lib.php
  view/accident/accident_card.php
  view/accident/accident_metadata.php
  view/accident/accident_metadata_lesion.php
  view/accidentinvestigation/accidentinvestigation_card.php
  view/digiriskelement/digiriskelement_card.php
  view/digiriskelement/digiriskelement_evaluator.php
  view/digiriskelement/digiriskelement_listingrisksaction.php
  view/digiriskelement/digiriskelement_listingrisksphoto.php
  view/digiriskelement/digiriskelement_organization.php
  view/digiriskelement/digiriskelement_register.php
  view/digiriskelement/digiriskelement_risk.php
  view/digiriskelement/digiriskelement_risksign.php
  view/digiriskstandard/digiriskstandard_informationssharing.php
  view/digiriskstandard/digiriskstandard_legaldisplay.php
  view/firepermit/firepermit_card.php
  view/preventionplan/preventionplan_card.php
Labels: Amélioration, 2

#3374 #3371 [JS] fix: timespent add refresh
  js/digiriskdolibarr.min.js
  js/modules/task.js
Labels: Bug, 1

#3375 #3359 [Ticket] fix: public interface configuration
  admin/ticket/ticket.php
Labels: Bug, 1

#3383 #3341 [Trad] fix: missing trad PP and FP
  langs/fr_FR/digiriskdolibarr.lang
Labels: Traduction, 0

#3384 #3380 [Documents] fix: set event message href
  class/digiriskelement.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
  view/digiriskelement/digiriskelement_card.php
  view/digiriskelement/digiriskelement_listingrisksaction.php
  view/digiriskelement/digiriskelement_listingrisksphoto.php
Labels: Amélioration, 2

#3381 #3378 [SQL] fix: remove deprecated triggers
  sql/data.sql
  sql/update.sql
Labels: Amélioration, 0

#3388 #3387 [JS] fix: rebuild js
  js/digiriskdolibarr.min.js
Labels: 0, JS

#3385 #3382 [Mod] fix: remove underscore and make compatibility
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/mod_accidentinvestigationdocument_standard.php
  core/modules/modDigiriskDolibarr.class.php
  sql/accidentinvestigation/llx_c_accidentinvestigation_attendants_role.sql
  sql/update.sql
Labels: Bug, 1

#3413 #3410 [Accident] fix: display and document generate issues
  class/accident.class.php
  class/accidentinvestigation.class.php
  core/modules/modDigiriskDolibarr.class.php
  view/accident/accident_card.php
  view/accidentinvestigation/accidentinvestigation_card.php
Labels: Bug, 2

#3414 #3409 [Translation] fix: missing rights translation
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 0

#3415 #3402 [ProjectCreation] fix: require thirdparty and project
  core/tpl/digiriskdolibarr_projectcreation_action.tpl.php
Labels: Bug, 1

#3416 #3412 [Documents] fix: require subdir if class in subdir
  class/digiriskdocuments.class.php
Labels: Bug, 0

#3419 #3411 [Mod] fix: various fix for accident/dashboard/lib
  class/accident.class.php
  class/digirisktask.class.php
  class/riskanalysis/risk.class.php
  core/modules/digiriskdolibarr/accidentinvestigation/mod_accidentinvestigation_peggy.php
  core/modules/digiriskdolibarr/digiriskelement/accident/mod_accident_curtiss.php
  core/modules/digiriskdolibarr/digiriskelement/accidentlesion/mod_accidentlesion_jarnsaxa.php
  core/modules/digiriskdolibarr/digiriskelement/accidentworkstop/mod_accidentworkstop_richthofen.php
  core/modules/digiriskdolibarr/digiriskelement/firepermit/mod_firepermit_bleriot.php
  core/modules/digiriskdolibarr/digiriskelement/firepermitdet/mod_firepermitdet_earhart.php
  core/modules/digiriskdolibarr/digiriskelement/preventionplan/mod_preventionplan_hinkler.php
  core/modules/digiriskdolibarr/digiriskelement/preventionplandet/mod_preventionplandet_alvaldi.php
  core/modules/modDigiriskDolibarr.class.php
  digiriskdolibarrindex.php
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr.lib.php
  lib/digiriskdolibarr_accident.lib.php
  lib/digiriskdolibarr_accidentinvestigation.lib.php
  lib/digiriskdolibarr_digiriskelement.lib.php
  lib/digiriskdolibarr_digiriskstandard.lib.php
  lib/digiriskdolibarr_firepermit.lib.php
  lib/digiriskdolibarr_preventionplan.lib.php
  lib/digiriskdolibarr_ticket.lib.php
  view/ticket/ticketstats.php
  view/ticket/ticketstatscsv.php
Labels: Bug, 3

#3422 #3421 [DigiriskStandard] fix: getpost subaction for gallery modal
  view/accident/accident_list.php
  view/digiriskelement/digiriskelement_evaluator.php
  view/digiriskelement/digiriskelement_listingrisksaction.php
  view/digiriskelement/digiriskelement_listingrisksphoto.php
  view/digiriskelement/digiriskelement_register.php
  view/digiriskelement/digiriskelement_risksign.php
  view/digiriskstandard/digiriskstandard_card.php
  view/digiriskstandard/digiriskstandard_informationssharing.php
  view/digiriskstandard/digiriskstandard_legaldisplay.php
  view/digiriskstandard/digiriskstandard_riskassessmentdocument.php
Labels: Bug, 1

#3424 #3404 [Risk] fix: various fix for riskAssessment/risk
  class/actions_digiriskdolibarr.class.php
  class/riskanalysis/riskassessment.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_inheritedrisklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  langs/fr_FR/digiriskdolibarr.lang
  test/phpunit/riskanalysis/RiskAssessmentUnitTest.php
Labels: Bug, 3

#3444 fix shared risks
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  lib/digiriskdolibarr_function.lib.php
  view/digiriskelement/digiriskelement_risk.php
Labels: Bug, 2

#3449 #3438 [ODT] fix: custom num ref for documents
  class/actions_digiriskdolibarr.class.php
  class/digiriskdolibarrdocuments/accidentinvestigationdocument.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/mod_accidentinvestigationdocument_siarnaq.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/firepermitdocument/mod_firepermitdocument_greip.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/groupmentdocument/mod_groupmentdocument_mundilfari.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/informationssharing/mod_informationssharing_gridr.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/legaldisplay/mod_legaldisplay_gerd.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksaction/mod_listingrisksaction_gunnlod.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksphoto/mod_listingrisksphoto_fornjot.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/preventionplandocument/mod_preventionplandocument_bestla.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/projectdocument/mod_projectdocument_angrboda.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/mod_riskassessmentdocument_eggther.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/ticketdocument/mod_ticketdocument_geirrod.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/workunitdocument/mod_workunitdocument_hati.php
  core/modules/modDigiriskDolibarr.class.php
Labels: Bug, 2

#3450 #3433 [Ticket] fix: fatal ticket prepare head
  lib/digiriskdolibarr_ticket.lib.php
  view/ticket/ticketstats.php
  view/ticket/ticketstatscsv.php
Labels: Bug, 1

#3451 #3429 [DigiriskStandard] fix: manage banner action
  view/digiriskelement/digiriskelement_listingrisksaction.php
  view/digiriskelement/digiriskelement_listingrisksphoto.php
  view/digiriskelement/digiriskelement_risksign.php
  view/digiriskstandard/digiriskstandard_card.php
  view/digiriskstandard/digiriskstandard_informationssharing.php
  view/digiriskstandard/digiriskstandard_legaldisplay.php
  view/digiriskstandard/digiriskstandard_riskassessmentdocument.php
Labels: Bug, 1

#3453 fix tasks
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  js/digiriskdolibarr.min.js
  js/modules/task.js
Labels: Bug, 3

#3442 #3428 [Trad] add: missing translations
  langs/fr_FR/digiriskdolibarr.lang
Labels: Traduction, 0

#3447 #3432 [RiskSign] fix: use new saturne class to edit modal
  core/tpl/riskanalysis/risksign/digiriskdolibarr_risksignlist_view.tpl.php
  js/digiriskdolibarr.min.js
  js/modules/form.js
  view/digiriskelement/digiriskelement_evaluator.php
Labels: Bug, 2

#3455 #3434 [Accident] fix: accident responsible role
  js/digiriskdolibarr.min.js
  view/accident/accident_card.php
Labels: Amélioration, 0

#3472 #3471 [RiskAssessmentDocument] fix: logo size on main page
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/doc_riskassessmentdocument_odt.modules.php
  documents/doctemplates/riskassessmentdocument/template_riskassessmentdocument.odt
Labels: Amélioration, 1

#3473 #3469 [Accident] fix: remove attendants creation
  view/accident/accident_card.php
Labels: Amélioration, 1

#3474 #3470 [DigiriskElement] fix: missing photo in banner tab
  class/actions_digiriskdolibarr.class.php
  view/accident/accident_list.php
Labels: Bug, 2

#3478 fix risks
  class/riskanalysis/risk.class.php
  view/digiriskelement/risk_list.php
Labels: Amélioration, 2

#3480 #3479 [DigiriskDocuments] fix: fatal on listings generation
  class/digiriskdocuments.class.php
Labels: Bug, 1

#3460 #3459 [Task] fix: change trigger label
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 0

#3475 #3468 [Task] fix: use saturne task for digirisk task
  class/actions_digiriskdolibarr.class.php
  class/api_digiriskdolibarr.class.php
  class/digiriskdolibarrdashboard.class.php
  class/digirisktask.class.php
  class/riskanalysis/risk.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_inheritedrisklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_sharedrisklist_view.tpl.php
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_single_view.tpl.php
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_view.tpl.php
  langs/fr_FR/digiriskdolibarr.lang
  view/digiriskelement/digiriskelement_risk.php
  view/digiriskelement/risk_list.php
  view/digirisktools.php
Labels: Amélioration, 3

#3484 fix version number
  README.md
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 1

#3491 #3490 [ODT] fix: change $related_task->fk_project by fk_projet due to SaturneTask
  class/digiriskdocuments.class.php
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_view.tpl.php
Labels: Bug, 2

#3497 fix minor bugs
  core/tpl/riskanalysis/risk/digiriskdolibarr_inheritedrisklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_sharedrisklist_view.tpl.php
  core/tpl/riskanalysis/risksign/digiriskdolibarr_inheritedrisksignlist_view.tpl.php
  core/tpl/riskanalysis/risksign/digiriskdolibarr_risksignlist_view.tpl.php
  core/tpl/riskanalysis/risksign/digiriskdolibarr_sharedrisksignlist_view.tpl.php
  css/digiriskdolibarr.css
  documents/doctemplates/informationssharing/template_informationssharing.odt
  public/ticket/create_ticket.php
  view/firepermit/firepermit_card.php
  view/preventionplan/preventionplan_card.php
Labels: Bug, Amélioration, 3
