Repository Evarisk/Digirisk, pull requests merged in 2023-06, with the labels that each got.

#3151 #3098 [Risk] add: update risk category name
  js/json/dangerCategories.json
  sql/update.sql
Labels: Amélioration, 2

#3152 #3109 #3134 [ODT] add: ticket message tags
  core/modules/digiriskdolibarr/digiriskdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
  core/modules/digiriskdolibarr/digiriskdocuments/riskassessmentdocument/modules_riskassessmentdocument.php
  documents/doctemplates/groupmentdocument/template_groupmentdocument.odt
  documents/doctemplates/riskassessmentdocument/template_riskassessmentdocument.odt
  documents/doctemplates/workunitdocument/template_workunitdocument.odt
Labels: Amélioration, 1, ODT/PDF

#3153 #3120 [ODT] fix: error generation on ticket tags
  core/modules/digiriskdolibarr/digiriskdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
  core/modules/digiriskdolibarr/digiriskdocuments/riskassessmentdocument/modules_riskassessmentdocument.php
Labels: Bug, 1, ODT/PDF

#3154 #3123 [Dashboard] fix: remove class info-box-sm
  class/dashboarddigiriskstats.class.php
Labels: Bug, 1

#3156 #3128 [Mod] add: wiki help url
  admin/config/about.php
  admin/config/accident.php
  admin/config/digiriskdocuments.php
  admin/config/digiriskelement.php
  admin/config/digirisksignature.php
  admin/config/firepermit.php
  admin/config/preventionplan.php
  admin/config/riskassessmentdocument.php
  admin/securityconf.php
  admin/setup.php
  admin/socialconf.php
  admin/ticket/ticket.php
  digiriskdolibarrindex.php
  view/accident/accident_agenda.php
  view/accident/accident_attendants.php
  view/accident/accident_card.php
  view/accident/accident_document.php
  view/accident/accident_document_metadata.php
  view/accident/accident_list.php
  view/accident/accident_metadata.php
  view/accident/accident_metadata_lesion.php
  view/digiriskelement/digiriskelement_agenda.php
  view/digiriskelement/digiriskelement_card.php
  view/digiriskelement/digiriskelement_evaluator.php
  view/digiriskelement/digiriskelement_listingrisksaction.php
  view/digiriskelement/digiriskelement_listingrisksphoto.php
  view/digiriskelement/digiriskelement_organization.php
  view/digiriskelement/digiriskelement_register.php
  view/digiriskelement/digiriskelement_risk.php
  view/digiriskelement/digiriskelement_risksign.php
  view/digiriskelement/risk_list.php
  view/digiriskstandard/digiriskstandard_agenda.php
  view/digiriskstandard/digiriskstandard_card.php
  view/digiriskstandard/digiriskstandard_informationssharing.php
  view/digiriskstandard/digiriskstandard_legaldisplay.php
  view/digiriskstandard/digiriskstandard_riskassessmentdocument.php
  view/digirisktools.php
  view/digiriskusers.php
  view/firepermit/firepermit_agenda.php
  view/firepermit/firepermit_attendants.php
  view/firepermit/firepermit_card.php
  view/firepermit/firepermit_list.php
  view/firepermit/firepermit_schedule.php
  view/openinghours_card.php
  view/preventionplan/preventionplan_agenda.php
  view/preventionplan/preventionplan_attendants.php
  view/preventionplan/preventionplan_card.php
  view/preventionplan/preventionplan_list.php
  view/preventionplan/preventionplan_schedule.php
  view/ticket/dashboard_ticket.php
  view/ticket/ticketstats.php
  view/ticket/ticketstatscsv.php
Labels: Amélioration, 2

#3157 #3129 [Trad] add: change trad 'cotation' by 'evaluation'
  admin/config/riskassessmentdocument.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view.tpl.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view_edit_modal.tpl.php
  langs/en_US/digiriskdolibarr.lang
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 1

#3160 #3159 [Core] fix: require_once with __DIR__
  digiriskdolibarrindex.php
  lib/digiriskdolibarr_function.lib.php
  view/digiriskelement/digiriskelement_agenda.php
  view/digiriskelement/digiriskelement_card.php
  view/digiriskelement/digiriskelement_evaluator.php
  view/digiriskelement/digiriskelement_listingrisksaction.php
  view/digiriskelement/digiriskelement_organization.php
  view/digiriskelement/digiriskelement_register.php
  view/digiriskelement/digiriskelement_risk.php
  view/digiriskelement/digiriskelement_risksign.php
  view/digiriskstandard/digiriskstandard_agenda.php
  view/digiriskstandard/digiriskstandard_informationssharing.php
  view/digiriskstandard/digiriskstandard_legaldisplay.php
  view/digiriskstandard/digiriskstandard_riskassessmentdocument.php
  view/digirisktools.php
  view/firepermit/firepermit_schedule.php
  view/openinghours_card.php
  view/preventionplan/preventionplan_schedule.php
Labels: Bug, 1

#3170 #3099 [Img] add: change pictos INRS + add 2 new pictos
  img/categorieDangers/activitePhysique_v2.png
  img/categorieDangers/amiante_v2.png
  img/categorieDangers/autre_PictoCategorie_v2.png
  img/categorieDangers/chuteH_PictoCategorie_v2.png
  img/categorieDangers/chutePP_PictoCategorie_v2.png
  img/categorieDangers/circulation_PictoCategorie_v2.png
  img/categorieDangers/circulation_v2.png
  img/categorieDangers/climat_PictoCategorie_v2.png
  img/categorieDangers/eclairage_PictoCategorie_v2.png
  img/categorieDangers/effondrement_PictoCategorie_v2.png
  img/categorieDangers/electricite_PictoCategorie_v2.png
  img/categorieDangers/heurt_PictoCategorie_v2.png
  img/categorieDangers/incendies_PictoCategorie_v2.png
  img/categorieDangers/machine_PictoCategorie_v2.png
  img/categorieDangers/manqueHygiene_PictoCategorie_v2.png
  img/categorieDangers/manutentionMe_PictoCategorie_v2.png
  img/categorieDangers/nuisances_PictoCategorie_v2.png
  img/categorieDangers/produitsC_PictoCategorie_v2.png
  img/categorieDangers/rayonnement_v2.png
  img/categorieDangers/rps_v2.png
  img/categorieDangers/vibration_PictoCategorie_v2.png
  img/categorieDangers/vibrations_v2.png
Labels: Amélioration, 3

#3171 #3169 [Mod] add: new version number 9.11.0
  README.md
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 0
