Repository Evarisk/Digirisk, pull requests merged in 2023-11, with the labels that each got.

#3140 #624 [PreventionPlan] add: plus button pp/fp
  view/firepermit/firepermit_card.php
  view/preventionplan/preventionplan_card.php
Labels: Amélioration, 2

#3143 #3084 #3085 [Conf] fix: minor issues
  class/actions_digiriskdolibarr.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/projectdocument/pdf_orque_projectdocument.modules.php
  core/modules/modDigiriskDolibarr.class.php
Labels: Bug, Amélioration, 1

#3530 #3529 [ODT] fix: missing photo on ticketdocument
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/ticketdocument/doc_ticketdocument_odt.modules.php
Labels: Bug, 1

#3534 #3531 [PreventionPlan] fix: deletion from list
  class/firepermit.class.php
  class/preventionplan.class.php
  view/firepermit/firepermit_list.php
  view/preventionplan/preventionplan_list.php
Labels: Bug, 2

#3543 fix media gallery display
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view.tpl.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view_edit_modal.tpl.php
  js/digiriskdolibarr.min.js
  js/modules/risk.js
  view/digiriskelement/digiriskelement_risk.php
Labels: Amélioration, 3

#3559 #3517 [RiskAssessment] fix: risk assessment comment wordbreak
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view_single.tpl.php
Labels: Bug, 2

#3566 #3149 [RiskAssessment] fix: shown risk assessment cotation values
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view.tpl.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view_edit_modal.tpl.php
  js/digiriskdolibarr.min.js
  js/modules/riskAssessment.js
Labels: Amélioration, 2

#3546 #3540 [Accident] add: accident register document
  admin/ticket/ticket.php
  class/accident.class.php
  class/actions_digiriskdolibarr.class.php
  class/digiriskdolibarrdocuments/registerdocument.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/doc_accidentinvestigationdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/registerdocument/doc_registerdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/registerdocument/index.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/registerdocument/mod_registerdocument_gridr.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/registerdocument/mod_registerdocument_standard.php
  core/modules/digiriskdolibarr/digiriskelement/accidentlesion/mod_accidentlesion_wright.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/accident/digiriskdolibarr_accident_lesion.tpl.php
  core/tpl/accident/digiriskdolibarr_accident_lesion_actions.tpl.php
  core/tpl/digiriskdolibarr_projectcreation_action.tpl.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
  documents/doctemplates/registerdocument/index.php
  documents/doctemplates/registerdocument/template_registerdocument.odt
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_accident.lib.php
  lib/digiriskdolibarr_digiriskstandard.lib.php
  sql/accident/llx_digiriskdolibarr_accident.sql
  sql/data.sql
  sql/llx_c_accident_attendants_role.sql
  sql/update.sql
  view/accident/accident_card.php
  view/accident/accident_list.php
  view/accident/accident_metadata_lesion.php
  view/accidentinvestigation/accidentinvestigation_card.php
  view/digiriskstandard/digiriskstandard_registerdocument.php
Labels: Amélioration, 3

#3583 #3580 [Accident] fix: backward user victim
  class/accident.class.php
Labels: Amélioration, 2

#3584 #3579 [RegisterDocument] fix: document page number
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/registerdocument/doc_registerdocument_odt.modules.php
  documents/doctemplates/registerdocument/template_registerdocument.odt
Labels: Amélioration, 1

#3575 #3568 [Ticket] add: viewfield linked accidents
  class/actions_digiriskdolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 1

#3585 #3578 [Accident] fix: minor issues
  class/accident.class.php
  class/accidentinvestigation.class.php
  view/accident/accident_card.php
  view/accidentinvestigation/accidentinvestigation_card.php
Labels: Bug, 1

#3577 #3576 [README] fix: version number and date
  README.md
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 0
