Repository Evarisk/Digirisk, pull requests merged in 2023-09, with the labels that each got.

#3229 #3228 [Triggers] add: improve trigger code to be like saturne
  admin/config/event.php
  class/accident_investigation.class.php
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 3

#3235 #3234 [Accident] fix: clean code, typo and improve perfomance
  class/accident_investigation.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/doc_accidentinvestigationdocument_odt.modules.php
  documents/doctemplates/accidentinvestigationdocument/template_accidentinvestigationdocument.odt
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_accident_investigation.lib.php
  sql/accident/llx_digiriskdolibarr_accident_investigation.sql
  view/accident_investigation/accident_investigation_card.php
Labels: Bug, Amélioration, 3

#3246 #3243 [Triggers] fix: change dictionary with good column and code according to
  admin/config/event.php
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
  langs/fr_FR/digiriskdolibarr.lang
  sql/data.sql
  sql/llx_c_digiriskdolibarr_action_trigger.key.sql
  sql/llx_c_digiriskdolibarr_action_trigger.sql
  sql/update.sql
Labels: Amélioration, 2

#3230 #3005 [LegalDisplayDocument] fix: improve linebreak
  documents/doctemplates/informationssharing/template_informationssharing.odt
  documents/doctemplates/legaldisplay/template_legaldisplay.odt
Labels: Amélioration, 0, ODT/PDF

#3242 #2782 [Accident] add: accident rework
  class/accident.class.php
  core/modules/modDigiriskDolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_accident.lib.php
  view/accident/accident_agenda.php
  view/accident/accident_attendants.php
  view/accident/accident_card.php
  view/accident/accident_document.php
  view/accident/accident_document_metadata.php
  view/accident/accident_list.php
  view/accident/accident_metadata.php
  view/accident/accident_metadata_lesion.php
Labels: Amélioration, 3

#3218 #3195 [PublicTicket] add: global require mods
  public/ticket/create_ticket.php
Labels: Amélioration, 1

#3245 #3243 [Investigation] fix: change workflow again
  class/accident_investigation.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/doc_accidentinvestigationdocument_odt.modules.php
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
  documents/doctemplates/accidentinvestigationdocument/template_accidentinvestigationdocument.odt
  langs/fr_FR/digiriskdolibarr.lang
  sql/accident/llx_digiriskdolibarr_accident_investigation.sql
  sql/data.sql
  view/accident_investigation/accident_investigation_card.php
Labels: Amélioration, 2

#3261 #3248 [Triggers] fix: require_once risk when task modify
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Bug, 1

#3258 #3250 [JSON] fix: import danger category digirisk wordpress
  js/json/dangerCategories.json
Labels: Bug, 1

#3225 #3190 [Core] fix: editor config
  .editorconfig
Labels: Amélioration, 0

#3224 #2933 [Task] add: auto affect task creator to DU project & created task
  admin/config/riskassessmentdocument.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
  langs/fr_FR/digiriskdolibarr.lang
  view/digiriskelement/digiriskelement_risk.php
Labels: Amélioration, 3

#3262 #3252 [Accident] add: integrate saturne on other accident related tab
  class/accident.class.php
  class/accident_investigation.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_accident.lib.php
  public/signature/add_signature.php
  view/accident/accident_card.php
  view/accident/accident_metadata.php
  view/accident/accident_metadata_lesion.php
  view/accident_investigation/accident_investigation_list.php
Labels: Amélioration, 3

#3292 #3291 [SQL] fix: change tms in current_timestamp
  sql/accident/llx_digiriskdolibarr_accident.sql
  sql/accident/llx_digiriskdolibarr_accident_extrafields.sql
  sql/accident/llx_digiriskdolibarr_accident_investigation.sql
  sql/accident/llx_digiriskdolibarr_accident_lesion.sql
  sql/accident/llx_digiriskdolibarr_accident_workstop.sql
  sql/accident/llx_digiriskdolibarr_accident_workstop_extrafields.sql
  sql/accident/llx_digiriskdolibarr_accidentmetadata.sql
  sql/digiriskelement/llx_digiriskdolibarr_digiriskelement.sql
  sql/digiriskelement/llx_digiriskdolibarr_digiriskelement_extrafields.sql
  sql/firepermit/llx_digiriskdolibarr_firepermit.sql
  sql/firepermit/llx_digiriskdolibarr_firepermit_extrafields.sql
  sql/firepermit/llx_digiriskdolibarr_firepermitdet.sql
  sql/firepermit/llx_digiriskdolibarr_firepermitdet_extrafields.sql
  sql/llx_digiriskdolibarr_digiriskresources.sql
  sql/llx_digiriskdolibarr_digiriskstandard.sql
  sql/llx_digiriskdolibarr_digiriskstandard_extrafields.sql
  sql/llx_digiriskdolibarr_evaluator.sql
  sql/llx_digiriskdolibarr_evaluator_extrafields.sql
  sql/preventionplan/llx_digiriskdolibarr_preventionplan.sql
  sql/preventionplan/llx_digiriskdolibarr_preventionplan_extrafields.sql
  sql/preventionplan/llx_digiriskdolibarr_preventionplandet.sql
  sql/preventionplan/llx_digiriskdolibarr_preventionplandet_extrafields.sql
  sql/riskanalysis/llx_digiriskdolibarr_risk.sql
  sql/riskanalysis/llx_digiriskdolibarr_risk_extrafields.sql
  sql/riskanalysis/llx_digiriskdolibarr_riskassessment.sql
  sql/riskanalysis/llx_digiriskdolibarr_riskassessment_extrafields.sql
  sql/riskanalysis/llx_digiriskdolibarr_risksign.sql
  sql/riskanalysis/llx_digiriskdolibarr_risksign_extrafields.sql
  sql/update.sql
Labels: Amélioration, 1

#3295 #3294 [Translation] fix: accident and investigation trad
  langs/fr_FR/digiriskdolibarr.lang
Labels: Traduction
