Repository Evarisk/Digirisk, pull requests merged in 2024-06, with the labels that each got.

#3954 #3953 [Hook] fix: saturne admindocuments
  class/actions_digiriskdolibarr.class.php
Labels: Bug, 0

#3960 #3959 [Trad] fix: trad firepermit
  view/firepermit/firepermit_card.php
Labels: Bug, 0

#3968 #3967 [Hook] fix: need change condition due to use strong hook like main
  class/actions_digiriskdolibarr.class.php
Labels: Bug, 2

#3978 #3977 [PublicTicket] fix: change hook name because already used
  class/actions_digiriskdolibarr.class.php
  core/modules/modDigiriskDolibarr.class.php
  public/ticket/create_ticket.php
Labels: Bug, 1

#3964 #3963 [Class] fix: remove typage on $isextrafieldmanaged and resprints
  class/accident.class.php
  class/accidentinvestigation.class.php
  class/actions_digiriskdolibarr.class.php
  class/digiriskelement.class.php
  class/digiriskresources.class.php
  class/digiriskstandard.class.php
  class/evaluator.class.php
  class/firepermit.class.php
  class/preventionplan.class.php
  class/riskanalysis/risk.class.php
  class/riskanalysis/riskassessment.class.php
  class/riskanalysis/risksign.class.php
Labels: Bug, 1

#3965 #3941 [ODT] fix: move signature on FP/PP
  documents/doctemplates/firepermitdocument/template_firepermitdocument.odt
  documents/doctemplates/preventionplandocument/template_preventionplandocument.odt
Labels: Amélioration, 1, ODT/PDF

#3974 #3973 [PP/FP] fix: location translation should be GP/UT
  view/firepermit/firepermit_card.php
  view/preventionplan/preventionplan_card.php
Labels: Traduction, 0

#3981 #3970 [Medias] add: title to describe buttons
  view/accident/accident_card.php
  view/accidentinvestigation/accidentinvestigation_card.php
  view/digiriskelement/digiriskelement_card.php
Labels: Amélioration, 1

#3976 #3864 [Audit] add: recipient field
  class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/auditreportdocument/doc_auditreportdocument_odt.modules.php
  view/digiriskstandard/digiriskstandard_auditreportdocument.php
Labels: Amélioration, 2

#4003 #4002 [Ticket] fix: use action create instead of specific
  class/actions_digiriskdolibarr.class.php
Labels: Bug, 0

#4008 #4007 [Mod] add: new version 10.2.1
  README.md
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 0
