Repository Evarisk/Digirisk, pull requests merged in 2024-02, with the labels that each got.

#3692 #3691 [RiskList] add: conf to display all risk parents
  admin/config/riskassessmentdocument.php
  class/riskanalysis/risk.class.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_sharedrisklist_view.tpl.php
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 2

#3699 #3698 [DigiriskDocument] add: every risk parent element in fillRiskData
  class/digiriskdocuments.class.php
Labels: Amélioration, 2

#3687 #3686 [Conf] fix: allow to select project related to a thirdparty too
  admin/config/accident.php
  admin/config/firepermit.php
  admin/config/preventionplan.php
  admin/config/riskassessmentdocument.php
  admin/ticket/ticket.php
Labels: Bug, 0

#3675 #3674 [Triggers] fix: missing require risk in task_create trigger
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Bug, 0

#3701 #3700 [JS] fix: improve task id selector
  js/digiriskdolibarr.min.js
  js/modules/task.js
Labels: Bug, 1, JS

#3696 #3694 [TemplateUpdateMask] add: template update mask
  admin/config/accident.php
  admin/config/digiriskelement.php
  admin/config/firepermit.php
  admin/config/preventionplan.php
  admin/config/riskassessmentdocument.php
Labels: Amélioration, 0

#3697 #3695 [UtGp] fix: width of the navigation container
  lib/digiriskdolibarr_function.lib.php
Labels: Bug, 1

#3708 #3705 [ModRiskSignGreip] fix: remove useless info function in risk sign mod file
  core/modules/digiriskdolibarr/riskanalysis/risksign/mod_risksign_greip.php
Labels: Amélioration, 0

#3680 #3676 [ListingRisksDocument] add: document listing for all model at time
  class/actions_digiriskdolibarr.class.php
  class/digiriskdolibarrdocuments/listingrisksdocument.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksaction_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksphoto_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/index.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/mod_listingrisksdocument_calypso.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/mod_listingrisksdocument_standard.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/modules_listingrisksdocument.php
  core/modules/modDigiriskDolibarr.class.php
  documents/doctemplates/listingrisksdocument/index.php
  documents/doctemplates/listingrisksdocument/listingrisksaction/index.php
  documents/doctemplates/listingrisksdocument/listingrisksaction/template_listingrisksaction.odt
  documents/doctemplates/listingrisksdocument/listingrisksdocument/index.php
  documents/doctemplates/listingrisksdocument/listingrisksdocument/template_listingrisksdocument.odt
  documents/doctemplates/listingrisksdocument/listingrisksphoto/index.php
  documents/doctemplates/listingrisksdocument/listingrisksphoto/template_listingrisksphoto.odt
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_digiriskelement.lib.php
  lib/digiriskdolibarr_digiriskstandard.lib.php
  sql/data.sql
  view/digiriskelement/digiriskelement_listingrisksaction.php
  view/digiriskelement/digiriskelement_listingrisksdocument.php
  view/digiriskelement/digiriskelement_listingrisksphoto.php
Labels: Amélioration, 5, ODT/PDF

#3681 #3678 [Document] fix: delete modules_digiriskdocuments.php file
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/modules_digiriskdocuments.php
Labels: Amélioration, 1
