Repository Evarisk/Digirisk, pull requests merged in 2024-03, with the labels that each got.

#3726 #3725 [Module] fix: remove useless file
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/modules_accidentinvestigationdocument.php
Labels: Amélioration, 0

#3710 #3185 [Langs] fix: visibility of names inside risk origin text
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 0

#3728 #3715 [Module] fix: bug for the ticket generation in UT part
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
Labels: Bug, 1

#3731 #3730 [ODT] add: rules_location in legal display
  core/substitutions/functions_digiriskdolibarr.lib.php
  documents/doctemplates/legaldisplay/template_legaldisplay.odt
Labels: Amélioration, 1, ODT/PDF

#3741 #3740 [FirePermit / PreventionPlan] fix: bug in the config part
  admin/config/accident.php
  admin/config/digiriskelement.php
  admin/config/firepermit.php
  admin/config/preventionplan.php
Labels: Bug, 3

#3727 #3706 [TicketDocument] fix: rework for use saturne
  class/actions_digiriskdolibarr.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/ticketdocument/doc_ticketdocument_odt.modules.php
  lib/digiriskdolibarr_function.lib.php
Labels: Amélioration, 2

#3744 #3743 [Class] fix: do not type fk_user_creat and fk_user_modif
  class/accidentinvestigation.class.php
Labels: Bug, 0

#3729 #1133 [ODT] add: audit report document
  class/actions_digiriskdolibarr.class.php
  class/digiriskdolibarrdocuments/auditreportdocument.class.php
  class/digiriskelement.class.php
  class/riskanalysis/risk.class.php
  class/riskanalysis/risksign.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/doc_accidentinvestigationdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/auditreportdocument/doc_auditreportdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/auditreportdocument/index.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/auditreportdocument/mod_auditreportdocument_lindberg.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/auditreportdocument/mod_auditreportdocument_standard.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/modules_listingrisksdocument.php
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
  documents/doctemplates/auditreportdocument/index.php
  documents/doctemplates/auditreportdocument/template_auditreportdocument.odt
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_digiriskstandard.lib.php
  sql/data.sql
  view/digiriskelement/digiriskelement_listingrisksdocument.php
  view/digiriskstandard/digiriskstandard_auditreportdocument.php
  view/digiriskstandard/digiriskstandard_riskassessmentdocument.php
Labels: Amélioration, 8

#3750 #3738 #3746 [Mod] fix: rework custom ref
  core/modules/digiriskdolibarr/accidentinvestigation/mod_accidentinvestigation_peggy.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/mod_accidentinvestigationdocument_siarnaq.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/firepermitdocument/mod_firepermitdocument_greip.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/groupmentdocument/mod_groupmentdocument_mundilfari.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/informationssharing/mod_informationssharing_gridr.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/legaldisplay/mod_legaldisplay_gerd.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksaction/mod_listingrisksaction_gunnlod.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/mod_listingrisksdocument_calypso.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksphoto/mod_listingrisksphoto_fornjot.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/preventionplandocument/mod_preventionplandocument_bestla.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/projectdocument/mod_projectdocument_angrboda.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/registerdocument/mod_registerdocument_thiazzi.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/mod_riskassessmentdocument_eggther.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/ticketdocument/mod_ticketdocument_geirrod.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/workunitdocument/mod_workunitdocument_hati.php
  core/modules/digiriskdolibarr/digiriskelement/accident/mod_accident_curtiss.php
  core/modules/digiriskdolibarr/digiriskelement/accidentlesion/mod_accidentlesion_wright.php
  core/modules/digiriskdolibarr/digiriskelement/accidentworkstop/mod_accidentworkstop_richthofen.php
  core/modules/digiriskdolibarr/digiriskelement/evaluator/mod_evaluator_bebhionn.php
  core/modules/digiriskdolibarr/digiriskelement/firepermit/mod_firepermit_bleriot.php
  core/modules/digiriskdolibarr/digiriskelement/firepermitdet/mod_firepermitdet_earhart.php
  core/modules/digiriskdolibarr/digiriskelement/groupment/mod_groupment_sirius.php
  core/modules/digiriskdolibarr/digiriskelement/preventionplan/mod_preventionplan_hinkler.php
  core/modules/digiriskdolibarr/digiriskelement/preventionplandet/mod_preventionplandet_alvaldi.php
  core/modules/digiriskdolibarr/digiriskelement/workunit/mod_workunit_canopus.php
  core/modules/digiriskdolibarr/riskanalysis/risk/mod_risk_tarqeq.php
  core/modules/digiriskdolibarr/riskanalysis/riskassessment/mod_riskassessment_jarnsaxa.php
  core/modules/digiriskdolibarr/riskanalysis/risksign/mod_risksign_greip.php
Labels: Amélioration, 1, Rework

#3690 #3684 [SQL] fix: insure trigger unicity in event auto table
  sql/data.sql
  sql/update.sql
Labels: Bug, 1

#3749 #3745 [TPL] fix: missing parameters check
  core/tpl/digiriskdolibarr_projectcreation_action.tpl.php
Labels: Bug, 1

#3753 #3752 [Core] fix: remove creation of custom odt document
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/digiriskdolibarr_projectcreation_action.tpl.php
Labels: Bug, 0

#3713 #3693 [WorkUnit] add: new conf to alterate wu document & modify display
  admin/config/riskassessmentdocument.php
  class/digiriskdocuments.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/workunitdocument/doc_workunitdocument_odt.modules.php
  core/modules/modDigiriskDolibarr.class.php
  documents/doctemplates/accidentinvestigationdocument/template_accidentinvestigationdocument.odt
  documents/doctemplates/groupmentdocument/template_groupmentdocument.odt
  documents/doctemplates/informationssharing/template_informationssharing.odt
  documents/doctemplates/listingrisksdocument/listingrisksaction/template_listingrisksaction.odt
  documents/doctemplates/listingrisksdocument/listingrisksdocument/template_listingrisksdocument.odt
  documents/doctemplates/listingrisksdocument/listingrisksphoto/template_listingrisksphoto.odt
  documents/doctemplates/preventionplandocument/template_preventionplandocument.odt
  documents/doctemplates/workunitdocument/template_workunitdocument.odt
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 3

#3755 #3754 [ODT] fix: reset after conflict merge
  documents/doctemplates/legaldisplay/template_legaldisplay.odt
Labels: Amélioration, 1, ODT/PDF
