Repository Evarisk/Digirisk, pull requests merged in 2024-10, with the labels that each got.

#4104 #4062 [Ticket] fix: fatal ticket conflict context in public and view
  class/actions_digiriskdolibarr.class.php
Labels: Bug, 0

#4115 #3983 [Dashboard] fix: reorder graphs
  class/digiriskdolibarrdashboard.class.php
  class/riskanalysis/risk.class.php
Labels: Amélioration, 0

#4116 #4112 [Dashboard] fix: new traductions
  langs/fr_FR/digiriskdolibarr.lang
Labels: 0

#4117 #4112 [Dashboard] fix: improve request
  class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
Labels: Amélioration, 0

#4119 #4118 [Img] add: pwa/default img
  img/digiriskdolibarr.png
  img/digiriskdolibarr_color.png
  img/digiriskdolibarr_color.svg
  img/digiriskdolibarr_color_192.png
  img/digiriskdolibarr_color_512.png
  img/digiriskdolibarr_logo.png
  img/object_digiriskdolibarr_color.png
Labels: Amélioration, 1

#4120 #4062 [Ticket] fix: fatal dashboard
  view/ticket/ticketstats.php
Labels: Bug, 0

#4084 #4079 [Card] fix: accident gauge
  class/accident.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/doc_accidentinvestigationdocument_odt.modules.php
  view/accident/accident_card.php
  view/accident/accident_list.php
  view/accidentinvestigation/accidentinvestigation_card.php
Labels: Bug, 1

#4121 #4107 [Risk] fix: navigation need type
  core/modules/modDigiriskDolibarr.class.php
  lib/digiriskdolibarr_function.lib.php
Labels: Bug, 1

#4122 #4088 [Ticket] fix: trad ticket child category
  core/modules/modDigiriskDolibarr.class.php
Labels: Traduction, 0

#4124 #4123 [RiskAssessmentTask] add: improve fields and design
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_view.tpl.php
Labels: Amélioration, 1

#4125 #4112 [Dashboard] fix: moreparam for dashboard request
  class/accident.class.php
  class/evaluator.class.php
  class/riskanalysis/risk.class.php
Labels: Amélioration, 1

#4127 #4112 [Dasboard] fix: fatal risk data
  class/riskanalysis/risk.class.php
Labels: Bug, 1

#4128 #4062 [Ticket] fix: fatal generation ticket
  class/actions_digiriskdolibarr.class.php
Labels: Bug, 0

#4129 #4089 [ODT] add: hour on date field for ticket with events
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/ticketdocument/doc_ticketdocument_odt.modules.php
Labels: Amélioration, 1, ODT/PDF

#4065 #3991 [Audit] add: change pre-filling date
  view/digiriskstandard/digiriskstandard_auditreportdocument.php
Labels: Amélioration, 1

#4135 #4102 [Dashboard] fix: riskAssessmentDocument date issue and color
  class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
Labels: Bug, 1

#4131 #4126 [RiskList] fix: bad page on edit evaluation
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
Labels: Bug, 2

#4132 #4130 [TicketDashboard] fix: bad number and purcentage on ticket dashboard
  class/digiriskdolibarrdashboard.class.php
  class/ticketdashboard.class.php
Labels: Bug, 2

#4144 #4143 [Hook] fix: remove userlist printFieldListWhere
  class/actions_digiriskdolibarr.class.php
Labels: Bug, 1
