Repository Evarisk/Digirisk, pull requests merged in 2024-11, with the labels that each got.

#4156 #4154 [RiskAssessmentDocumentDashboard] fix: remove no delay for next generation to avoid confustion
  class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
Labels: Bug, 0

#4149 #3969 [Lists] fix: column don't remove when unchecked
  class/riskanalysis/risk.class.php
  class/riskanalysis/riskassessment.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_inheritedrisklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_sharedrisklist_view.tpl.php
  js/digiriskdolibarr.min.js
  js/modules/form.js
Labels: Bug, 3

#4137 #4083 [Dashboard] add: name and filter on graphs
  class/accident.class.php
  class/digiriskelement.class.php
  class/riskanalysis/risk.class.php
  class/ticketdashboard.class.php
Labels: Amélioration, 3

#4170 #4169 [Admin] fix: remove imgTabTitle override
  admin/config/riskassessmentdocument.php
  admin/event.php
  css/digiriskdolibarr.min.css
  css/scss/style.scss
Labels: 0, Rework

#4059 #4043 [RiskAssessmentTask] add: remove task button on single view if no task
  class/riskanalysis/risk.class.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view.tpl.php
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_view.tpl.php
  langs/fr_FR/digiriskdolibarr.lang
  view/digirisktools.php
Labels: Amélioration, 0

#4168 #4167 [Mod] add: DigiBoard require
  core/modules/modDigiriskDolibarr.class.php
Labels: Amélioration, 0

#4176 #4175 [Risk] fix: missing riskassessment-task and modal-footer on container
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
Labels: Bug, 1
