Repository Evarisk/Digirisk, pull requests merged in 2024-01, with the labels that each got.

#3662 #3656 [Risk] fix: dir_output from the riskassessment entity and not conf
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view_single.tpl.php
Labels: Bug, 1

#3663 #3659 [DigiriskElement] fix: select_digirisk_element_list sql filter
  view/digiriskelement/digiriskelement_card.php
Labels: Bug, 0

#3651 #2599 [Mod] fix: backward wu become ut
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/workunitdocument/mod_workunitdocument_standard.php
  core/modules/digiriskdolibarr/digiriskelement/workunit/mod_workunit_standard.php
  core/modules/modDigiriskDolibarr.class.php
Labels: Amélioration, 2

#3661 #3654 [Document] fix: require projectdocument custom
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/projectdocument/pdf_orque_projectdocument.modules.php
Labels: Bug, 0, ODT/PDF

#3664 #3660 [DigiriskElement] fix: fetchAll with entity parameter
  view/digiriskelement/digiriskelement_organization.php
Labels: Bug, 0

#3665 #3641 [Mod] add: update release date
  README.md
Labels: Amélioration, 0
