Repository Evarisk/Digirisk, pull requests merged in 2024-08, with the labels that each got.

#4070 #4067 [Tools] fix: clean risk and riskassessment and graphs
  class/riskanalysis/risk.class.php
  class/riskanalysis/riskassessment.class.php
  langs/fr_FR/digiriskdolibarr.lang
  view/digirisktools.php
Labels: Bug, 8

#4071 #3646 [Dashboard] add : Add download button for risk assessment document
  class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
Labels: Amélioration, 3

#4076 #4075 [Hook] fix: parameters photoLimit
  class/actions_digiriskdolibarr.class.php
Labels: Bug, 0
