Repository Evarisk/Digirisk, pull requests merged in 2024-12, with the labels that each got.

#4196 #4194 [Digiboard] fix: no data when nothing in bin
  class/riskanalysis/risk.class.php
Labels: Bug, 0

#4166 #4098 #4139 fix: extrafields errors and rework extraFieldsArrays
  admin/ticket/ticket.php
  class/actions_digiriskdolibarr.class.php
  core/modules/modDigiriskDolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_function.lib.php
Labels: Bug, 2

#3997 #3721 [PublicTicket] add: signature page on ticket
  admin/ticket/ticket.php
  class/actions_digiriskdolibarr.class.php
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
  css/digiriskdolibarr.min.css
  css/scss/page/_ticket.scss
  js/digiriskdolibarr.min.js
  js/modules/ticket.js
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_function.lib.php
  public/ticket/create_ticket.php
  view/ticket/category_config.php
Labels: Amélioration, 3

#4199 #4198 [DocumentClass] fix: position of label in actions documents
  class/digiriskdocuments.class.php
Labels: Amélioration, 1

#4200 #3721 [Hook] fix: fatal picto with formObjectOptions
  class/actions_digiriskdolibarr.class.php
Labels: Bug, 0

#4172 #4171 [Dashbord] clean: php8 warning
  class/accident.class.php
  class/actions_digiriskdolibarr.class.php
  class/digiriskdolibarrdashboard.class.php
  class/digiriskdolibarrdocuments/informationssharing.class.php
  class/digiriskdolibarrdocuments/legaldisplay.class.php
  class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
  class/digiriskelement.class.php
  class/digiriskresources.class.php
  class/evaluator.class.php
  class/firepermit.class.php
  class/preventionplan.class.php
  class/riskanalysis/risk.class.php
  class/ticketdashboard.class.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_sharedrisklist_view.tpl.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view.tpl.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view_edit_modal.tpl.php
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_single_view.tpl.php
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_view.tpl.php
  lib/digiriskdolibarr_function.lib.php
  view/accident/accident_list.php
  view/digiriskelement/risk_list.php
  view/digiriskusers.php
  view/firepermit/firepermit_list.php
  view/preventionplan/preventionplan_list.php
Labels: Amélioration, 13

#4140 #2004 [DigiriskTools] add: js and loader for import
  js/digiriskdolibarr.min.js
  js/modules/tools.js
  langs/fr_FR/digiriskdolibarr.lang
  view/digirisktools.php
Labels: Amélioration, 3

#4158 #4142 [TicketStatsDashboard] add: stats tickets graph and widgets
  class/digiriskdolibarrdashboard.class.php
  class/ticketstatsdashboard.class.php
  langs/fr_FR/digiriskdolibarr.lang
  view/ticket/dashboard_ticketstats.php
Labels: Amélioration, 5

#4203 #4142 [TicketDashboard] fix: tab for navigate and rework view
  class/ticketstatsdashboard.class.php
  core/modules/modDigiriskDolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_ticket.lib.php
  view/ticket/dashboard_ticket.php
  view/ticket/dashboard_ticketstats.php
  view/ticket/ticket_management_dashboard.php
Labels: Bug, 2

#4207 #4142 [Trad] fix: missing trad
  admin/ticket/ticket.php
  langs/fr_FR/digiriskdolibarr.lang
Labels: Traduction, 0

#4208 #4206 [Mod] add: new version number 20.0.0
  README.md
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 0

#4226 #4225 [Dashboard] fix: repair filter
  class/riskanalysis/risk.class.php
Labels: Bug, 0
