Repository Evarisk/Digirisk, pull requests merged in 2024-05, with the labels that each got.

#3857 #3856 [RiskAssessment] fix: update environmental risk cotations
  class/riskanalysis/riskassessment.class.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view_edit_modal.tpl.php
  js/digiriskdolibarr.min.js
  js/json/default.json
  js/modules/riskAssessment.js
Labels: Bug, 1, JS

#3873 #3872 [JS] fix: remove useless file
  js/digiriskdolibarr.min.js
  js/modules/button.js
Labels: Bug, 0, JS

#3851 #3781 [Dashboard] add: graphs, widgets and list with stats and infos
  admin/config/digiriskelement.php
  class/digiriskdolibarrdashboard.class.php
  class/digiriskelement.class.php
  class/riskanalysis/risk.class.php
  core/modules/modDigiriskDolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_digiriskelement.lib.php
  view/digiriskelement/digiriskelement_informations.php
Labels: Amélioration, 5

#3870 #3866 [Accident] fix: fk_ticket in create view
  view/accident/accident_card.php
Labels: Bug, 1

#3874 #3865 [ODT] fix: sanitize br for ticket document event content
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/ticketdocument/doc_ticketdocument_odt.modules.php
Labels: Bug, 2, ODT/PDF

#3878 #3863 [ODT] fix: date range error
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/auditreportdocument/doc_auditreportdocument_odt.modules.php
Labels: Bug, 5, ODT/PDF

#3879 #3877 [PublicTicket] fix: rework ticket success
  langs/fr_FR/digiriskdolibarr.lang
  public/ticket/ticket_success.php
Labels: Amélioration, 2, Rework

#3875 #3876 [Ticketstats] fix: rework graph and the ticket stats data and also create a list in the new load dashbaord
  class/digiriskdolibarrdashboard.class.php
  class/digiriskelement.class.php
  class/digiriskstats.php
  class/ticketdashboard.class.php
  class/ticketdigiriskstats.class.php
  digiriskdolibarrindex.php
  langs/fr_FR/digiriskdolibarr.lang
  view/digiriskelement/digiriskelement_informations.php
  view/digiriskstandard/digiriskstandard_card.php
  view/ticket/ticketstats.php
  view/ticket/ticketstatscsv.php
Labels: Amélioration, 5, Rework

#3861 #3854 [Hook] add: firepermit object to linked control
  class/actions_digiriskdolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 2

#3883 #3881 [Trad] fix: listingrisk and projectenvironment translation
  langs/fr_FR/digiriskdolibarr.lang
  view/digiriskelement/digiriskelement_listingrisksdocument.php
Labels: Traduction, 0

#3885 #3884 [Dashboard] fix: use template instead of repetitive actions
  view/digiriskelement/digiriskelement_informations.php
  view/digiriskstandard/digiriskstandard_card.php
Labels: Amélioration, 1

#3889 #3888 [Trigger] fix: replace </br> by <br> for document print purpose
  class/accidentinvestigation.class.php
  class/actions_digiriskdolibarr.class.php
  class/digiriskdocuments.class.php
  class/preventionplan.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/ticketdocument/doc_ticketdocument_odt.modules.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_sharedrisklist_view.tpl.php
  langs/fr_FR/digiriskdolibarr.lang
  public/ticket/create_ticket.php
  view/accidentinvestigation/accidentinvestigation_card.php
Labels: Bug, 0

#3897 #3896 [Audit] fix: fatal because missing require when generate document
  view/digiriskstandard/digiriskstandard_auditreportdocument.php
Labels: Bug, 0

#3880 #3862 [Mod] add: new version number 10.1.0
  README.md
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 0

#3909 #3364 [ProjectDocument] fix: change hook action and use builddoc saturne
  class/actions_digiriskdolibarr.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/projectdocument/pdf_orque_projectdocument.modules.php
Labels: Bug, 3, ODT/PDF

#3882 #3791 [Configuration] fix: use object element instead of type
  admin/config/firepermit.php
  admin/config/preventionplan.php
Labels: Bug, 3

#3887 #3624 [AccidentInvestigation] fix: transnoentities mandatory for insert SQL
  view/accidentinvestigation/accidentinvestigation_card.php
Labels: Bug, 1

#3907 #3905 [Admin] fix: use global $mc instead of $conf->mc because remove in 19
  admin/config/riskassessmentdocument.php
  class/digiriskdocuments.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_view.tpl.php
  view/digiriskelement/digiriskelement_risk.php
  view/digiriskelement/risk_list.php
Labels: Bug, 2

#3910 #3900 [Risk] fix: remove class for prevent conflict JS with mediaGallery
  view/digiriskelement/digiriskelement_risk.php
Labels: Bug, 1

#3914 #3912 [Ticket] fix: action generate csv need getpost
  view/ticket/ticketstats.php
Labels: Bug, 0

#3908 #3903 [Admin] fix: init conf on if/elseif dont reset or use previous value
  core/modules/modDigiriskDolibarr.class.php
Labels: Bug, 3

#3911 #2963 [Documents] fix: pdf orque task label should not overlap on budget
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/projectdocument/pdf_orque_projectdocument.modules.php
Labels: Bug, 1

#3921 #3920 [Risk] fix: digirisk element selector need a maxwidth
  class/actions_digiriskdolibarr.class.php
  class/digiriskelement.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_inheritedrisklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_sharedrisklist_view.tpl.php
  core/tpl/riskanalysis/risksign/digiriskdolibarr_inheritedrisksignlist_view.tpl.php
  core/tpl/riskanalysis/risksign/digiriskdolibarr_sharedrisksignlist_view.tpl.php
  view/accident/accident_card.php
  view/digiriskelement/digiriskelement_card.php
  view/firepermit/firepermit_card.php
  view/preventionplan/preventionplan_card.php
Labels: Bug, 1

#3925 #3918 [PublicTicket] fix: add manifest file for PWA
  class/actions_digiriskdolibarr.class.php
  core/modules/modDigiriskDolibarr.class.php
  img/digiriskdolibarr_color.svg
  img/digiriskdolibarr_color_192.png
  img/digiriskdolibarr_color_512.png
  lib/digiriskdolibarr.lib.php
  manifest.json.php
Labels: Amélioration, 2

#3926 #3923 [RiskAssessmentDocument] add: filter on GP/UT on tickets
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/doc_riskassessmentdocument_odt.modules.php
Labels: Amélioration, 1, ODT/PDF

#3927 #3924 [Risk] fix: set massactionbutton even with filter
  core/tpl/riskanalysis/risk/digiriskdolibarr_inheritedrisklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_sharedrisklist_view.tpl.php
  core/tpl/riskanalysis/risksign/digiriskdolibarr_inheritedrisksignlist_view.tpl.php
  core/tpl/riskanalysis/risksign/digiriskdolibarr_risksignlist_view.tpl.php
  core/tpl/riskanalysis/risksign/digiriskdolibarr_sharedrisksignlist_view.tpl.php
  view/digiriskelement/digiriskelement_evaluator.php
Labels: Bug, 0

#3943 #3933 [ConfigTicket] use reposition and page_y
  admin/ticket/ticket.php
Labels: Bug, 2

#3945 #3944 [Mod] add: new version number 10.2.0
  README.md
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 0
