Repository Evarisk/Digirisk, pull requests merged in 2024-07, with the labels that each got.

#3993 #3987 [Risk] fix: update task modal budget in JS
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
  js/digiriskdolibarr.min.js
  js/modules/task.js
Labels: Bug, 2, JS

#4011 #3988 [Risk] add: sql query order by fk_object
  class/riskanalysis/risk.class.php
Labels: Amélioration, 2

#4013 #4012 [DigiriskElement] fix: gp and wu odt documents
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/workunitdocument/doc_workunitdocument_odt.modules.php
  documents/doctemplates/groupmentdocument/template_groupmentdocument.odt
  documents/doctemplates/workunitdocument/template_workunitdocument.odt
Labels: Bug, 1, ODT/PDF

#3958 #3937 [PP/FP] add: contact signatories in recipient for mail
  view/firepermit/firepermit_card.php
  view/preventionplan/preventionplan_card.php
Labels: Amélioration, 3

#4030 #4022 [Tools] fix: need to reset risk->type on default value
  view/digirisktools.php
Labels: Bug, 1

#4029 #4024 [Index] fix: moreParams wrong initialization value
  digiriskdolibarrindex.php
Labels: Bug, 1

#4031 #4022 [Tools] fix: Missing risk status
  view/digirisktools.php
Labels: Bug, 1

#4033 #4032 [Conf] fix: wrong variable check
  admin/config/riskassessmentdocument.php
Labels: Bug, 0

#4035 #4027 [Core] add: set poison control centers in digirisk resources
  core/modules/modDigiriskDolibarr.class.php
Labels: Amélioration, 1

#4037 #4028 [Core] add: update right defenders information
  core/modules/modDigiriskDolibarr.class.php
Labels: Amélioration, 1

#4045 #4044 [Lang] fix: wrong trad on back translate
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 0

#4048 #4023 [Risk] fix: set date_creation of risk and evaluation the same as date_riskassessment
  view/digirisktools.php
Labels: Amélioration, 2

#4056 #3802 [CSS] add: CSS list GP UT
  css/digiriskdolibarr.min.css
  css/scss/page/_page-ut-gp-list.scss
  css/scss/responsive/_page-ut-gp-list.scss
Labels: Amélioration, 1, Integration, IHM

#4052 #4020 [JS] fix: task progress in modal
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_view.tpl.php
  js/digiriskdolibarr.min.js
  js/modules/task.js
Labels: Bug, 3, JS

#4047 #4046 [Conf] add: replace mobile trans for landline
  admin/securityconf.php
Labels: Bug, 1

#4058 #4055 [Lib] fix: wrong html on a in function digirisk_header
  lib/digiriskdolibarr_function.lib.php
Labels: Bug, 0

#4061 #4060 [ODT] fix: keep title of the array through pages
  documents/doctemplates/riskassessmentdocument/template_riskassessmentdocument.odt
Labels: Amélioration, 0, ODT/PDF
