Repository Evarisk/Digirisk, pull requests merged in 2024-04, with the labels that each got.

#3756 #3754 [Odt] fix: modify the opening hours for labour doctor and detective work for
  class/digiriskdolibarrdocuments/legaldisplay.class.php
  core/substitutions/functions_digiriskdolibarr.lib.php
  documents/doctemplates/legaldisplay/template_legaldisplay.odt
Labels: Amélioration, 2, ODT/PDF

#3759 #3758 [ODT] fix: new exception OdfExceptionSegmentNotFound and remove version attribute and phpmin
  admin/ticket/ticket.php
  class/digiriskdocuments.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/doc_accidentinvestigationdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/auditreportdocument/doc_auditreportdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/firepermitdocument/doc_firepermitdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/groupmentdocument/doc_groupmentdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/informationssharing/doc_informationssharing_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/legaldisplay/doc_legaldisplay_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksaction_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksphoto_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/preventionplandocument/doc_preventionplandocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/registerdocument/doc_registerdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/doc_riskassessmentdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/ticketdocument/doc_ticketdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/workunitdocument/doc_workunitdocument_odt.modules.php
  core/modules/modDigiriskDolibarr.class.php
  lib/digiriskdolibarr.lib.php
  lib/digiriskdolibarr_digiriskelement.lib.php
  lib/digiriskdolibarr_digiriskstandard.lib.php
  public/ticket/create_ticket.php
  public/ticket/ticket_success.php
Labels: Bug, 3

#3761 #3760 [Mod] fix: wrong parameter and need conf before use it
  core/modules/digiriskdolibarr/riskanalysis/risksign/mod_risksign_greip.php
  core/modules/modDigiriskDolibarr.class.php
Labels: Bug, 0

#3766 #3765 [Mod] add: Export all object
  core/modules/modDigiriskDolibarr.class.php
Labels: Amélioration, 2

#3776 #3693 [ODT] fix: documents format and table repetition
  class/digiriskdocuments.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/auditreportdocument/doc_auditreportdocument_odt.modules.php
  core/substitutions/functions_digiriskdolibarr.lib.php
  documents/doctemplates/auditreportdocument/template_auditreportdocument.odt
  documents/doctemplates/firepermitdocument/template_firepermitdocument.odt
  documents/doctemplates/groupmentdocument/template_groupmentdocument.odt
  documents/doctemplates/listingrisksdocument/listingrisksaction/template_listingrisksaction.odt
  documents/doctemplates/listingrisksdocument/listingrisksdocument/template_listingrisksdocument.odt
  documents/doctemplates/listingrisksdocument/listingrisksphoto/template_listingrisksphoto.odt
  documents/doctemplates/preventionplandocument/template_preventionplandocument.odt
  documents/doctemplates/riskassessmentdocument/template_riskassessmentdocument.odt
  documents/doctemplates/ticketdocument/template_ticketdocument_events.odt
  documents/doctemplates/workunitdocument/template_workunitdocument.odt
Labels: Bug, 2

#3788 #3751 [Mod] add: new version number 9.15.0
  README.md
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 0

#3805 #3652 [Json] add: update for use risk and risk environmental
  class/riskanalysis/risk.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view.tpl.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view_edit_modal.tpl.php
  js/json/dangerCategories.json
  js/json/default.json
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_digiriskelement.lib.php
  sql/riskanalysis/llx_digiriskdolibarr_risk.sql
  sql/update.sql
  view/digiriskelement/digiriskelement_risk.php
Labels: Amélioration, 2

#3804 #3770 [RiskEnvironmental] add: SQL/Class type field
  class/riskanalysis/risk.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_digiriskelement.lib.php
  sql/riskanalysis/llx_digiriskdolibarr_risk.sql
  sql/update.sql
  view/digiriskelement/digiriskelement_risk.php
Labels: Amélioration, 5, Data model

#3780 #3736 [ODT] add environnemental risk report
  documents/doctemplates/listingriskenvironmentalaction/index.php
  documents/doctemplates/listingriskenvironmentalaction/template_listingriskenvironmentalsaction.odt
Labels: 2

#3808 #3807 [ODT] add: listings risk environmental action
  class/actions_digiriskdolibarr.class.php
  class/digiriskdolibarrdocuments/listingrisksenvironmentalaction.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksenvironmentalaction_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksenvironmentalaction/index.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksenvironmentalaction/mod_listingrisksenvironmentalaction_jocaste.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksenvironmentalaction/mod_listingrisksenvironmentalaction_standard.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/digiriskdolibarr_projectcreation_action.tpl.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
  documents/doctemplates/listingriskenvironmentalaction/template_listingriskenvironmentalsaction.odt
  documents/doctemplates/listingrisksdocument/listingrisksenvironmentalaction/index.php
  documents/doctemplates/listingrisksdocument/listingrisksenvironmentalaction/template_listingrisksenvironmentalaction.odt
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_digiriskelement.lib.php
  sql/data.sql
  view/digiriskelement/digiriskelement_listingrisksdocument.php
Labels: Amélioration, 3, ODT/PDF

#3797 #3732 [DigiriskElement] fix: better hierarchy display
  class/digiriskdocuments.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_sharedrisklist_view.tpl.php
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 0

#3800 #3799 [Actions] add: chek on remove_file to avoid problems in gmao and other projects
  class/actions_digiriskdolibarr.class.php
Labels: Amélioration, 0

#3145 #2677 [RiskAssessmentDocument] add: multiselect recipient
  class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/digiriskdocuments/digiriskdolibarr_riskassessmentdocumentfields_view.tpl.php
  view/digiriskstandard/digiriskstandard_riskassessmentdocument.php
Labels: Amélioration, 2

#3794 #1963 [Risk] add: category on risks
  admin/config/riskassessmentdocument.php
  class/actions_digiriskdolibarr.class.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/riskassessment/digiriskdolibarr_riskassessment_view_single.tpl.php
  js/digiriskdolibarr.min.js
  js/modules/risk.js
  langs/fr_FR/digiriskdolibarr.lang
  sql/riskanalysis/llx_categorie_risk.key.sql
  sql/riskanalysis/llx_categorie_risk.sql
  view/digiriskelement/digiriskelement_risk.php
  view/digiriskelement/risk_list.php
Labels: Amélioration, 3

#3795 #2738 [Documents] add: total tasks budget on model orque and change sort order
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/projectdocument/pdf_orque_projectdocument.modules.php
Labels: Amélioration, 2

#3796 #2962 [Document] add: conf to display riskassessment in color orque pdf
  class/actions_digiriskdolibarr.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/projectdocument/pdf_orque_projectdocument.modules.php
  core/modules/modDigiriskDolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 1

#3809 #3652 [IMG] add: picto risks environmental
  img/categorieDangers/Pictogrammes_environnement_divers.png
  img/categorieDangers/Pictogrammes_environnement_energie_emise.png
  img/categorieDangers/Pictogrammes_environnement_matieres_premieres.png
  img/categorieDangers/Pictogrammes_environnement_production_dechets.png
  img/categorieDangers/Pictogrammes_environnement_rejets_air.png
  img/categorieDangers/Pictogrammes_environnement_rejets_eau.png
  img/categorieDangers/Pictogrammes_environnement_rejets_sol.png
  img/categorieDangers/Pictogrammes_environnement_utilisation_energie.png
  img/categorieDangers/Pictogrammes_environnement_utilisation_espace.png
  js/json/dangerCategories.json
Labels: Amélioration, 5

#3821 #3819 [Risk] fix: clean code after environmental integration
  class/actions_digiriskdolibarr.class.php
  core/tpl/digiriskdolibarr_projectcreation_action.tpl.php
  sql/data.sql
  view/digiriskelement/digiriskelement_risk.php
Labels: Bug, 0

#3825 #3824 [Mod] fix: export riskassessment need risks permissions
  core/modules/modDigiriskDolibarr.class.php
Labels: Bug, 0

#3827 #3826 [Document] fix: fetch and sort riskassessment in projectdoc orque
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/projectdocument/pdf_orque_projectdocument.modules.php
Labels: Bug, 0

#3814 #3807 [ODT] fix: filter risk on type
  class/riskanalysis/risk.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/doc_accidentinvestigationdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/auditreportdocument/doc_auditreportdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksaction_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksenvironmentalaction_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksphoto_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/doc_riskassessmentdocument_odt.modules.php
Labels: Bug, 2

#3837 #3813 [Risk] fix: sql parameters and trad
  core/tpl/riskanalysis/risk/digiriskdolibarr_inheritedrisklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_sharedrisklist_view.tpl.php
  langs/fr_FR/digiriskdolibarr.lang
  view/digiriskelement/digiriskelement_risk.php
Labels: Amélioration, 2

#3817 #3810 [Menu] add: environmental risks menu
  core/modules/modDigiriskDolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
  view/digiriskelement/risk_list.php
Labels: Amélioration, 2

#3842 #3812 [ODT] fix: change img for listing risk env
  documents/doctemplates/listingrisksenvironmentaldocument/listingrisksenvironmentalaction/template_listingrisksenvironmentalaction.odt
Labels: Amélioration, 2, Integration

#3844 #3807 [ODT] fix: listings risk env
  documents/doctemplates/listingrisksenvironmentaldocument/listingrisksenvironmentalaction/template_listingrisksenvironmentalaction.odt
Labels: 1, ODT/PDF

#3845 #3843 [Risk] add: trad and picto for risk
  class/riskanalysis/risk.class.php
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_digiriskelement.lib.php
  lib/digiriskdolibarr_digiriskstandard.lib.php
  view/digiriskelement/risk_list.php
Labels: Amélioration, 1

#3848 #3836 [Risk] fix: missing backtopage risk type
  view/digiriskelement/risk_list.php
Labels: Bug, 1

#3846 #3772 [RiskEnvironmental] add: environment project
  admin/config/riskassessmentdocument.php
  class/digiriskelement.class.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/digiriskdolibarr_projectcreation_action.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_inheritedrisklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_sharedrisklist_view.tpl.php
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_view.tpl.php
  langs/fr_FR/digiriskdolibarr.lang
  view/digiriskelement/digiriskelement_environment.php
  view/digirisktools.php
Labels: Amélioration, 3

#3847 #3841 [Mod] add: new version number 10.0.0
  README.md
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 0

#3850 #3812 #3849 [Img] fix: change picto
  core/modules/modDigiriskDolibarr.class.php
  img/categorieDangers/Pictogrammes_environnement_divers.png
  img/categorieDangers/Pictogrammes_environnement_energie_emise.png
  img/categorieDangers/Pictogrammes_environnement_matieres_premieres.png
  img/categorieDangers/Pictogrammes_environnement_production_dechets.png
  img/categorieDangers/Pictogrammes_environnement_rejets_air.png
  img/categorieDangers/Pictogrammes_environnement_rejets_eau.png
  img/categorieDangers/Pictogrammes_environnement_rejets_sol.png
  img/categorieDangers/Pictogrammes_environnement_utilisation_energie.png
  img/categorieDangers/Pictogrammes_environnement_utilisation_espace.png
Labels: 1, Integration

#3859 #3858 [ODT] fix: delete break line
  documents/doctemplates/workunitdocument/template_workunitdocument.odt
Labels: 1, ODT/PDF

#3860 #3858 [ODT] update break line and apply new information
  documents/doctemplates/groupmentdocument/template_groupmentdocument.odt
Labels: Amélioration, 1, ODT/PDF
