Repository Evarisk/Digirisk, pull requests merged in 2025-07, with the labels that each got.

#4471 #4439 [EvaluatorClass] fix: bad translation
  class/evaluator.class.php
Labels: Bug, 0

#4472 #4397 [Ticket] fix: use saturneMail instead of ModelMail object
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Bug, 1

#4473 #4409 [DigiriskElement] fix: change check on status
  view/digiriskelement/digiriskelement_card.php
Labels: Bug, 1

#4474 #4442 [Ticket] fix: CSS on card
  css/digiriskdolibarr.min.css
  css/scss/module/card/_card.scss
  public/ticket/create_ticket.php
Labels: Bug, 1

#4479 Add digi ai tab
  core/ajax/create_risk.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risk_actions.tpl.php
  css/digiriskdolibarr.min.css
  css/scss/page/_digiai.scss
  css/scss/page/_page.scss
  js/digiriskdolibarr.min.js
  js/modules/digiai.js
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_digiriskelement.lib.php
  view/digiriskelement/backend_endpoint_for_chatgpt.php
  view/digiriskelement/backend_endpoint_for_google_vision.php
  view/digiriskelement/digiriskelement_digiai.php
Labels: Amélioration, 8

#4482 #4481 [Lang] fix: missing translation PreventionPlanLinked
  langs/fr_FR/digiriskdolibarr.lang
Labels: Bug, 0

#4486 Eldy patch 1
  view/preventionplan/preventionplan_list.php
Labels: 1, IHM

#4502 Fix psychosocial risks
  class/riskanalysis/risk.class.php
  core/ajax/create_risk.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/doc_riskassessmentdocument_odt.modules.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_psychosocial_risk_modal.tpl.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_risklist_view.tpl.php
  documents/doctemplates/riskassessmentdocument/template_riskassessmentdocument.odt
  js/digiriskdolibarr.min.js
  js/json/dangerSubCategories.json
  js/modules/psychosocialRisk.js
  js/modules/psychosocialRisks.js
  js/modules/risk_table_common.js
  langs/fr_FR/digiriskdolibarr.lang
  sql/riskanalysis/llx_digiriskdolibarr_risk.sql
  sql/update.sql
  view/digiriskelement/digiriskelement_risk.php
Labels: Amélioration, 5
