Repository Evarisk/Digirisk, pull requests merged in 2025-08, with the labels that each got.

#4500 #4429 [PDF/RiskTask] fix: risk task by adding executive and also modify pdf
  class/actions_digiriskdolibarr.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/projectdocument/pdf_papripact_a3_paysage_projectdocument.modules.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_single_view.tpl.php
  css/digiriskdolibarr.min.css
  css/scss/table/_riskassessment-task.scss
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 3

#4504 #4503 [RiskAssessment] fix : bug on multi company
  class/actions_digiriskdolibarr.class.php
Labels: Bug, 1

#4039 #4026 [Mod] add: change labour doctor default name
  core/modules/modDigiriskDolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 2

#4501 #4366 [EnvrionmentRisk] add: rights on environment risk
  core/modules/modDigiriskDolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
  view/digiriskelement/risk_list.php
Labels: Amélioration, 2

#4511 #4506 [PDF] fix: papripact pdr and remove orque in categories
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/projectdocument/pdf_papripact_a3_paysage_projectdocument.modules.php
  core/modules/modDigiriskDolibarr.class.php
Labels: Amélioration, 2, ODT/PDF

#4521 #4520 [ODT] fix: mistake in the text of a title
  documents/doctemplates/riskassessmentdocument/template_riskassessmentdocument.odt
Labels: Amélioration, 0, ODT/PDF

#4540 #4539 [task modal] fix: update modal ux / ui
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_view.tpl.php
  css/digiriskdolibarr.min.css
  css/scss/modal/_riskassessment-task.scss
Labels: Amélioration, 3, IHM

#4535 #4525 [ActionDigiriskdolibarr] add: signature info on ticket card
  class/actions_digiriskdolibarr.class.php
  core/modules/modDigiriskDolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
  public/ticket/create_ticket.php
Labels: Amélioration, 3

#4552 #4551 [Ticket] fix: ticket condition message extrafields
  admin/ticket/ticket.php
  class/actions_digiriskdolibarr.class.php
  core/modules/modDigiriskDolibarr.class.php
  public/ticket/create_ticket.php
Labels: Bug, 2

#4564 #4533 [CategoryConfig] fix: IHM category config
  langs/fr_FR/digiriskdolibarr.lang
  view/ticket/category_config.php
Labels: 1

#4562 #4559 [DU] fix: typo
  documents/doctemplates/riskassessmentdocument/template_riskassessmentdocument.odt
Labels: 0

#4563 Add digiai enhances
  admin/config/digiai.php
  js/digiriskdolibarr.min.js
  js/modules/digiai.js
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr.lib.php
  view/digiriskelement/digiriskelement_digiai.php
Labels: Amélioration, 3

#4565 #4544 [ActionDigiriskDolibarr] fix: digiriskelement ticket edit
  class/actions_digiriskdolibarr.class.php
Labels: Bug, 2

#4566 #4542 [ModDigiriskDolibarr] fix: remove trashed digirisk element from list ticket create
  core/modules/modDigiriskDolibarr.class.php
  public/ticket/create_ticket.php
Labels: 2

#4569 #4558 [CSS] fix: fix min CSS
  css/digiriskdolibarr.min.css
  css/scss/page/_digiai.scss
  js/digiriskdolibarr.min.js
Labels: Bug, 0

#4572 #4571 [JS] fix: use saturneElement file for navigation
  js/digiriskdolibarr.min.js
  js/modules/navigation.js
  lib/digiriskdolibarr_function.lib.php
Labels: Bug, 1, JS
