Repository Evarisk/Digirisk, pull requests merged in 2025-03, with the labels that each got.

#4320 #4138 [DocRiskAssessment] fix: double risk in riskassessment doc and fix var not sent
  class/riskanalysis/risk.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/doc_riskassessmentdocument_odt.modules.php
Labels: Bug, 3

#4324 #4305 [TaskSingleView] add: number of linked files of the task
  core/tpl/riskanalysis/riskassessmenttask/digiriskdolibarr_riskassessment_task_single_view.tpl.php
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 2

#4321 #4304 [RiskClass] fix: getNomUrl link to 404
  class/riskanalysis/risk.class.php
Labels: Amélioration, 1

#4337 #4336 [Mod] fix: change sql filter for forgeSQLFromUniversalSearchCriteria
  admin/config/firepermit.php
  admin/config/preventionplan.php
  admin/securityconf.php
  admin/socialconf.php
  view/accident/accident_card.php
  view/accident/accident_metadata.php
  view/digiriskelement/digiriskelement_evaluator.php
  view/firepermit/firepermit_card.php
  view/preventionplan/preventionplan_card.php
Labels: Bug, 2
