Repository Evarisk/Digirisk, pull requests merged in 2025-05, with the labels that each got.

#4380 #4377 [ODT] add: rework riskassessmentdocument and more datas
  class/accident.class.php
  class/actions_digiriskdolibarr.class.php
  class/digiriskdocuments.class.php
  class/digiriskelement.class.php
  class/evaluator.class.php
  class/riskanalysis/risk.class.php
  class/ticketdashboard.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/auditreportdocument/doc_auditreportdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/doc_riskassessmentdocument_odt.modules.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/riskanalysis/risk/digiriskdolibarr_sharedrisklist_view.tpl.php
  digiriskdolibarrindex.php
  documents/doctemplates/groupmentdocument/template_groupmentdocument.odt
  documents/doctemplates/riskassessmentdocument/template_riskassessmentdocument.odt
  documents/doctemplates/workunitdocument/template_workunitdocument.odt
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_function.lib.php
  view/digiriskelement/digiriskelement_card.php
  view/digiriskelement/digiriskelement_risk.php
  view/digirisktools.php
Labels: Amélioration, 8, Rework

#4393 #4377 [ODT] fix: match tag photo error
  documents/doctemplates/listingrisksdocument/listingrisksdocument/template_listingrisksdocument.odt
  documents/doctemplates/listingrisksdocument/listingrisksphoto/template_listingrisksphoto.odt
Labels: Bug, 0, ODT/PDF

#4394 #4377 [ODT] fix: missing tag riskAssessment_photo in setRiskByRiskAssessmentLevelsSegment
  class/digiriskdocuments.class.php
Labels: Bug, 0, ODT/PDF

#4395 #4377 [ODT] fix: photo tag
  class/digiriskdocuments.class.php
  class/riskanalysis/risk.class.php
Labels: Amélioration, 0, ODT/PDF

#4401 #4312 [RiskAssessmentDocument] fix: improve generation/clean code
  class/actions_digiriskdolibarr.class.php
  class/digiriskdocuments.class.php
  class/digiriskstandard.class.php
  core/tpl/digiriskdocuments/digiriskdolibarr_riskassessmentdocumentfields_view.tpl.php
  lib/digiriskdolibarr_digiriskstandard.lib.php
  view/digiriskstandard/digiriskstandard_riskassessmentdocument.php
Labels: Amélioration, 3, ODT/PDF

#4402 #4312 [ODT] add: improve DU and setRiskByEntitiesSegment
  class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
  class/evaluator.class.php
  class/riskanalysis/risk.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/doc_riskassessmentdocument_odt.modules.php
  core/modules/modDigiriskDolibarr.class.php
  core/tpl/digiriskdocuments/digiriskdolibarr_riskassessmentdocumentfields_view.tpl.php
  documents/doctemplates/riskassessmentdocument/template_riskassessmentdocument.odt
  documents/doctemplates/workunitdocument/template_workunitdocument.odt
  view/digiriskstandard/digiriskstandard_riskassessmentdocument.php
Labels: Amélioration, 2, ODT/PDF

#4403 #4399 [Mod] add: new version number 21.0.0
  README.md
  core/modules/modDigiriskDolibarr.class.php
  core/triggers/interface_99_modDigiriskdolibarr_DigiriskdolibarrTriggers.class.php
Labels: Amélioration, 0

#4407 #4406 [Risk] fix: change parameter type in risk_type for prevent conflict
  class/digiriskelement.class.php
  class/riskanalysis/risk.class.php
  core/modules/modDigiriskDolibarr.class.php
  lib/digiriskdolibarr_digiriskelement.lib.php
  lib/digiriskdolibarr_function.lib.php
  view/digiriskelement/digiriskelement_risk.php
  view/digiriskelement/risk_list.php
Labels: Bug, 1

#4410 #4312 [ODT] fix: improve ODT generation
  class/accident.class.php
  class/actions_digiriskdolibarr.class.php
  class/digiriskdocuments.class.php
  class/digiriskdolibarrdocuments/riskassessmentdocument.class.php
  class/digiriskelement.class.php
  class/evaluator.class.php
  class/riskanalysis/risk.class.php
  class/riskanalysis/risksign.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/accidentinvestigationdocument/doc_accidentinvestigationdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/auditreportdocument/doc_auditreportdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/index.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/groupmentdocument/doc_groupmentdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksaction_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksphoto_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksenvironmentaldocument/doc_listingrisksenvironmentalaction_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/modules_digiriskdolibarrdocument.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/doc_riskassessmentdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/workunitdocument/doc_workunitdocument_odt.modules.php
  langs/fr_FR/digiriskdolibarr.lang
  lib/digiriskdolibarr_digiriskstandard.lib.php
  lib/digiriskdolibarr_function.lib.php
  lib/digiriskdolibarr_ticket.lib.php
  view/digiriskstandard/digiriskstandard_auditreportdocument.php
Labels: Bug, 3, ODT/PDF

#4418 #4385 #4164 [Trad] fix: missing translations or incorrect words
  class/accidentinvestigation.class.php
  js/json/default.json
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, Traduction, 1

#4419 #4285 [AccidentCard] add: victim in accident card and can update victim from update form
  class/actions_digiriskdolibarr.class.php
  view/accident/accident_card.php
Labels: Amélioration, 3
