Repository Evarisk/Digirisk, pull requests merged in 2025-01, with the labels that each got.

#4234 #4233 [ODT] fix: reset nophoto with no data
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
Labels: Bug, 1

#4229 #4228 [Langs] add : delete accident trad
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, Traduction, 0

#4212 #4202 [Odt] fix: add EE and EU in first add color and signature EE
  documents/doctemplates/preventionplandocument/template_preventionplandocument.odt
Labels: Amélioration, 2, ODT/PDF

#4260 #4259 [Ticket] fix: bug update ticket category config
  public/ticket/create_ticket.php
  view/ticket/category_config.php
Labels: Bug, 1

#4258 #4253 [DigiriskUserList] fix: no user in list
  view/digiriskusers.php
Labels: Bug, 0

#4261 #4162 [DefaultJson] fix: typo in question and description
  js/json/default.json
Labels: 0
