Repository Evarisk/Digirisk, pull requests merged in 2025-02, with the labels that each got.

#4256 #4236 [AccidentClassDashboard] fix: bad year with 2025
  class/accident.class.php
Labels: Bug, 1

#4254 #3936 [Accident] add: change status for create accident investigation
  view/accident/accident_card.php
Labels: Amélioration, 1

#4280 #4279 [RiskAssessmentDocument] fix: use function for rights
  view/digiriskstandard/digiriskstandard_riskassessmentdocument.php
Labels: Bug, 1

#4297 #4286 [AccidentCard] add: 0 days workstop
  class/accident.class.php
  langs/fr_FR/digiriskdolibarr.lang
  view/accident/accident_card.php
Labels: Amélioration, 1

#4296 #4287 [AccidentClass] fix: hide ReturnWorkDate when not locked
  class/accident.class.php
Labels: Amélioration, 0

#4295 #4288 [AccidentCard] fix: AccidentInvestigation always here
  view/accident/accident_card.php
Labels: Amélioration, 0

#4300 #4138 [ODT] add odt for shared risk
  documents/doctemplates/riskassessmentdocument/template_totalriskassessmentdocument.odt
Labels: 2

#4301 #4138 [RiskAssessmentDocument] add: new board for shared risks
  class/digiriskdocuments.class.php
  class/riskanalysis/risk.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/riskassessmentdocument/doc_riskassessmentdocument_odt.modules.php
  documents/doctemplates/riskassessmentdocument/template_riskassessmentdocument.odt
  documents/doctemplates/riskassessmentdocument/template_totalriskassessmentdocument.odt
  view/digiriskstandard/digiriskstandard_riskassessmentdocument.php
Labels: Amélioration, 3

#4309 #4308 [PreventionPlan] fix: outside and society are the same
  class/digiriskdolibarrdocuments/preventionplandocument.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/preventionplandocument/doc_preventionplandocument_odt.modules.php
  documents/doctemplates/preventionplandocument/template_preventionplandocument.odt
Labels: Bug, 2
