Repository Evarisk/Digirisk, pull requests merged in 2025-04, with the labels that each got.

#4349 #4348 [DigiriskDoc] fix: bad number of parameters function
  class/digiriskdocuments.class.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/digiriskelementdocument/modules_digiriskelementdocument.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksaction_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksdocument_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksdocument/doc_listingrisksphoto_odt.modules.php
  core/modules/digiriskdolibarr/digiriskdolibarrdocuments/listingrisksenvironmentaldocument/doc_listingrisksenvironmentalaction_odt.modules.php
Labels: Bug, 2

#4367 #4306 [Lib] add: change order for tab in digiriskelement
  lib/digiriskdolibarr_digiriskelement.lib.php
Labels: Amélioration, 1

#4368 #4340 [Hook] fix: check class before add picto on task extrafields
  class/actions_digiriskdolibarr.class.php
Labels: Bug, 0

#4369 #4283 [Accident] add: improve accident button in ticket card
  class/actions_digiriskdolibarr.class.php
  view/accident/accident_card.php
Labels: Amélioration, 1

#4290 #3721 [odt] add: template for ticket signature on line
  documents/doctemplates/ticketdocument/template_ticketdocument_event_sign.odt
  documents/doctemplates/ticketdocument/template_ticketdocument_sign.odt
Labels: 1, ODT/PDF

#4370 #4361 [ODT] add: New risk document with new design and dashboard
  documents/doctemplates/riskassessmentdocument/template_riskassessmentdocument.odt
Labels: 5

#4374 #3984 [Admin] add: Ticket Public interface URL config
  admin/ticket/ticket.php
  core/modules/modDigiriskDolibarr.class.php
  js/digiriskdolibarr.min.js
  js/modules/admin.js
  langs/fr_FR/digiriskdolibarr.lang
Labels: Amélioration, 3

#4270 #4269 [ActionDigiriskDolibarr] fix: no object ticket create
  class/actions_digiriskdolibarr.class.php
  langs/fr_FR/digiriskdolibarr.lang
Labels: Bug, 1
